### ISSUE TITLE
Repeated builds will generate larger app?

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw-builder#110]
I.e. if you build (let's say with a gulpfile), you might get a 100 KB `.exe`, then run it again, you'll get 130 KB (or something like that) and so on.

Not sure why this happens. Maybe it's concatenating them somehow or something. 

Should we clean the destination before doing anything?

**Comment by 1j01** [comment]
The build folder and cache folder should be automatically excluded when building, as well as any `devDependencies`
That way you wouldn't have to maintain duplicate `package.json` files.

**Comment by kisPocok** [comment]
We should skip _devDependencies_. +'

**Comment by blischalk** [comment]
I ran into this issue too and adding exclusions to the files property of NwBuilder seemed to help.

```javascript
var nw = new NwBuilder({
  files: ['./**/**', '!./build/**/**'], // use the glob format
  version: "0.12.0",
  platforms: ['osx32', 'osx64', 'win32', 'win64']
});
```

notice the !./build/**/**. I didn't think about excluding cache but I should add that too.
