### ISSUE TITLE
Window transparency not showing window after build

### ISSUE THREAD

**Issue by nwesoccer** [nwjs/nw-builder#151]
We have a transparent window using setTransparent(true).  When we gulp run() this window works just fine.  When we gulp build() with platform 'win' and then run outputed exe, the window never shows.

**Comment by martin-grand** [comment]
I set transparency with package.json, and I had a same issue.

**Comment by adam-lynch** [comment]
Does it work when running the app with [`nw`](https://www.npmjs.com/package/nw)?
