### ISSUE TITLE
NwBuilder.options.files needs rename

### ISSUE THREAD

**Issue by felixSchl** [nwjs/nw-builder#171]
The `NwBuilder` does not use the `options.files` verbatim, it runs it through a `Glob`. I ran into a case were I built my own grunt wrapper and grunt would already do the globbing for me and pass the desired files into nodewebkit.

I think we should either:

* Not glob
* Call `options.files` -> `options.fileglob`
* Opt-out via flag
* Only glob if filename is a glob pattern, i.e. has leading bang `!` or contains astrix characters `*`.

A rename would probably be the easiest way forward.

Why is this an issue? While the code - as it stands - can be considered "semantically correct", globbing a filepath with a thousand patterns (previously expanded filenames) is extremely slow.

**Comment by adam-lynch** [comment]
Couldn't this be solved by allowing a glob *or* an array of globs to be passed as the `files` parameter? Then you could just pass an array of file paths like:

```javascript
files: [
    './index.js',
    './index.html',
    './package.json'
] 
```

**Comment by felixSchl** [comment]
But that's exactly what we've got. The problem is that is being fed verbatim to `simpleglob` - which then takes a very long time to complete. We could pre-filter or try another library instead. I am aware this patch is introducing breaking changes and hence not too attractive. It would introduce subtle bugs if someone was to upgrade unknowingly - i.e. their files just won't expand.

**Comment by adam-lynch** [comment]
Yeah, a breaking change is definitely unattractive so like you said maybe speeding up what we have. Like, gulp, etc. supports the same kind of thing and isn't very slow. 

> simpleglob - which then takes a very long time to complete.

Very long relative to what? Compared to other libraries? Or you've timed this and it just seems to take too long?

**Comment by felixSchl** [comment]
I didn't time it, but it felt like an eternity of a difference. I haven't tried any other libraries, and I have not checked out the implementation of `simpleglob` so I don't know why it's so slow. But it has to do IO and that's always slow.

We could possibly pre-filter patterns from expanded paths somehow, i.e. looking at the globbing specs and filter items that do not qualify as being a globbing pattern.

**Comment by adam-lynch** [comment]
> an eternity of a difference.

Compared to what? Your PR?

**Comment by felixSchl** [comment]
Yes, that is correct. Again, I understand there might be other ways to go about it with a non-breaking changes, but this is by far the fastest to get done without added complexity of pre-filtering.

**Comment by adam-lynch** [comment]
Ok, I guess a breaking change is the least preferable option though. So hopefully it can be sped up. Alternatively, maybe it could be done without a breaking change; `files` could be a glob or an array of filepaths *if* another (new) property exists (maybe something like `globbing: false`).

**Comment by adam-lynch** [comment]
Thanks for reporting this and the PR, but I don't think this is a real problem that affects the typical user. Thanks again though.
