### ISSUE TITLE
winIco changes icon for .exe but not taskbar

### ISSUE THREAD

**Issue by nv-vn** [nwjs/nw-builder#187]
EXE: https://i.imgur.com/ejMSjE7.png
Taskbar: https://i.imgur.com/1FckoHc.png
ICO in question: http://a.pomf.se/vnlmtw.ico

Build script:
```javascript
var nwb = require('node-webkit-builder');

var nw = new nwb({
        files : ['./*', './*/*'],
        platforms : ['win32', 'win64'],
        winIco : './icons/icon.ico',
        buildDir : './build'
});

nw.on('log', console.log);
nw.build().then(function() {
        console.log('Done!');
}).catch(function(error) {
        console.error(error);
});
```

**Comment by felicienfrancois** [comment]
For the taskbar, this is the icon field of the package.json which is taken into account
https://github.com/nwjs/nw.js/wiki/Manifest-format#icon

**Comment by adam-lynch** [comment]
Are you sure @felicienfrancois? See https://github.com/nwjs/nw.js/wiki/Icons

**Comment by adam-lynch** [comment]
I have this problem myself but I thought maybe it was a problem with my `.ico`. To confirm, the icon is shown as the default one only when the icon is shown at the "medium" size, which can be in the taskbar (when the taskbar settings are to show "large icons") or in explorer (depending on file view settings).

**Comment by adam-lynch** [comment]
P.S. @felicienfrancois, I do have a PNG in that `icon` field in my `package.json` so I guess it's not that? Unless it has to be a specific size / smaller than a certain size?

**Comment by felicienfrancois** [comment]
Yes, I'm sure, I just made a test, with raw nw binaries, when I launch with a png image in `window.icon` package.json field I have an the image as icon in my taskbar and when I remove it I have the default icon.
Same for the icon at the top left corner of the window.
My png image is 256*256.
Test on windows 8.1.

The exe resource icon is only used in explorer

**Comment by adam-lynch** [comment]
Could you take a screenshot of the taskbar?


Regards,
Adam Lynch

**Comment by kessler** [comment]
Windows 8.1 and NW.js 0.11.5:

![image](https://cloud.githubusercontent.com/assets/147367/6545481/fb54ff36-c591-11e4-968e-8ee70da64144.png)

**Comment by adam-lynch** [comment]
Damn. Could you upload the ICO here and we'll try?

**Comment by kessler** [comment]
I used a png all around, or did I miss something?

**Comment by adam-lynch** [comment]
No, I'm just being stupid :)
