### ISSUE TITLE
winIco doesnt apply

### ISSUE THREAD

**Issue by No3x** [nwjs/nw-builder#203]
Hi guys,
I want to apply an icon to my release build but it is not integrated into the exe. Switched from nodebob to node-webkit-builder or to be exactly: grunt-node-webkit-builder.
I have tried several images and several image types but nothing is changing.
My config:
```
nodewebkit: {
            options: {
                build_dir: './dist',
                winIco: './app/app.ico',
                // specifiy what to build
                mac: false,
                win: true,
                linux32: false,
                linux64: false
            },
            src: './app/**/*'
        },
```
My folder structure:
```
package.json
Gruntfile.js
dist/
app/
 |-package.json
 |-index.html
 |-app.ico
```
I build on Win32.
Did not help:
```
ie4uinit.exe -ClearIconCache
```

**Comment by felicienfrancois** [comment]
What is your operating system (XP, Vista, seven, win8, ...) ?
Have you any error message in the console output ?
How did you made your icon file ?
Does your icon file includes at least the following sizes: 16x16, 32x32, 48x48 ?

Here a few tutorials to make a valid icon file:
http://stackoverflow.com/questions/4354617/how-to-make-get-a-multi-size-ico-file
http://zduck.com/2014/creating-ico-icon-for-windows-app/

**Comment by No3x** [comment]
It's Win7x86.
I tried the flash from https://github.com/mllrsohn/node-webkit-builder/issues/187#issuecomment-77758766
I tried hopefully proper firefox.ico http://people.mozilla.org/~faaborg/files/shiretoko/firefoxIcon/firefox.ico
I tried a png renamed to ico. 32x32px
I tried png. 32x32px
I tried ico. 32x32px, 128x128px
I tried bmp. 32x32px
The output is:
```
> setup@0.0.1 preinstall C:\ProgramData\nodebob\DemoDVD_Menu\app
> npm i -g opener

npm http request GET https://registry.npmjs.org/opener
npm http 304 https://registry.npmjs.org/opener
C:\Program Files\nodejs\opener -> C:\Program Files\nodejs\node_modules\opener\op
ener.js
opener@1.4.0 C:\Program Files\nodejs\node_modules\opener
Der Verzeichnisname ist ungültig.
Running "nodewebkit:src" (nodewebkit) task
C:\ProgramData\nodebob\DemoDVD_Menu\dist\releases\setup\win\setup\setup.exe C:\P
rogramData\nodebob\DemoDVD_Menu\dist\releases\setup\setup.nw win C:\ProgramData\
nodebob\DemoDVD_Menu\dist\cache\win\0.9.2\nw.exe
>> Created a new release with node-webkit (0.9.2) for win
>> @ C:\ProgramData\nodebob\DemoDVD_Menu\dist\releases\setup

Done, without errors.
```
The only error: Der Verzeichnisname ist ungültig. = The directory name is invalid. Comes from opener, i guess.

**Comment by felicienfrancois** [comment]
What command are you running to build it ?
Can you post the extract(s) of your grunt file using node-webkit-builder ?

**Comment by No3x** [comment]
You can see it in full length:
```
module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('app/package.json'),
        nodewebkit: {
            options: {
                build_dir: './dist',
                winIco: './app/app.ico',
                // specifiy what to build
                mac: false,
                win: true,
                linux32: false,
                linux64: false
            },
            src: './app/**/*'
        },
    });

    grunt.loadNpmTasks('grunt-node-webkit-builder');

    grunt.registerTask('default', ['nodewebkit']);
};
```
So

**Comment by felicienfrancois** [comment]
Sorry, I really not have the time to enquire more on your issue for now.
I may have a look later.
As a temporary workaround, you can disable winIco option and use https://github.com/felicienfrancois/node-winresourcer to set the icon afterward:
```
winresourcer: {
	operation: "Update",
	exeFile: "path/to/your/app.exe",
	resourceType: "Icongroup",
	resourceName: "IDR_MAINFRAME",
	resourceFile: "path/to/your/icon.ico"
},
```

**Comment by No3x** [comment]
As you said I applied this workaround:
```
module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('app/package.json'),
        nodewebkit: {
            options: {
                build_dir: './dist',
                winIco: './app/app.ico',
                // specifiy what to build
                mac: false,
                win: true,
                linux32: false,
                linux64: false
            },
            src: './app/**/*'
        },
        "winresourcer": {
            icon: {
                operation: "Update", // one of Add, Update, Extract or Delete
                exeFile: "<%= nodewebkit.options.build_dir %>/releases/setup/win/setup/setup.exe",
                resourceType: "Icongroup",
                resourceName: "IDR_MAINFRAME",
                lang: 1033, // Required, except when updating or deleting
                resourceFile: "<%= nodewebkit.options.winIco %>" // Required, except when deleting
            }
        }
    });

    grunt.loadNpmTasks('grunt-node-webkit-builder');

    grunt.loadNpmTasks('winresourcer');

    grunt.registerTask('default', ['nodewebkit', 'winresourcer:icon']);
};
```
I can easily confirm this error by enabling or disabling the winresourcer step.
When disabled the nw icons appears.
When enabled the wanted icon is included.

But there is a problem - nw doesnt want to start any more.
Cannot extract package 
Failed to unzip the package file: C:\ProgramData\nodebob\DemoDVD_Menu"\dist\releases\setup\win\setup\setup.exe
But I have to sort out if I'm misusing resourcer.

**Comment by niravjgandhi** [comment]
I also try this in my app but without the custom name in win icon i give the name call favicon.ico and its work for me.
nodewebkit: {
    options: {
	version:'0.12.1',
        build_dir: './webkitbuilds', // Where the build version of my node-webkit app is saved
        winIco: './favicon.ico',
		mac: false, // We want to build it for mac
        win: true, // We want to build it for win
        linux32: false, // We don't need linux32
        linux64: true, // We don't need linux64
        credits: './credits.html', // mac only, used to display credits
        mac_icns: './app.icns'
    },
    src: ['app/**/*'] // Your node-wekit app source directory
}

**Comment by matthew-dean** [comment]
Nw-builder doesn't seem to make an .exe file. Nsis does at the time of install. How would I build using nw-builder in a way that would make the .exe accessible (to try to fix the icon bug)?

**Comment by puzzud** [comment]
I spent a bit of time trying out a bunch of things:  different icon sizes and formats, playing with Resourcer.

I'm using Windows 7 and I too noticed various situations where the icon specified with winIco didn't always apply.

I eventually found something that works:  I used GIMP to create a 48x48 32 bit ICO file.

For some reason, Windows File Explorer doesn't want to show the updated icon for the Tiles file view. However, if you relocate the resulting NW executable, File Explorer shows it with the new icon. As far as I can tell, this situation is just File Explorer acting badly.

The default NW JS EXE icon reports itself as a 48x48 32 bit ICO. I noticed that when I messed with the EXE a bit with Resourcer, it was really easy to break the NW JS EXE, rendering it unable to run it with the embedded NW ZIP.

My guess is if you do not replace this image "exactly", it won't behave as expected.

Hope this helps.

**Comment by matthew-dean** [comment]
@puzzud Eager to try this out. Thanks for investigating!

**Comment by No3x** [comment]
@puzzud Thanks for your effort! I'll try to apply your suggestion if I have that set up quick again (I don't remember if i used nw-builder or nodebob at the end in this project) Can you share your ico?
>Can someone just send me over an as working known image, so that we can eliminate a problem with the resource itself?

**Comment by puzzud** [comment]
@No3x, icon here:
https://raw.githubusercontent.com/puzzud/gjweb/master/assets/graphics/icons/win/icon.ico

**Comment by matthew-dean** [comment]
This isn't fixed. After trying a zillion things, a thought occurred to me. I copied the nwjs.exe itself and ran that in Windows 10, and sure enough, the NW.js icon does NOT appear in the app. Meaning: even if you successfully replaced the nwjs icon image, it _still_ wouldn't work, because that icon is not displayed correctly in the app. The nwjs.exe file itself has broken icon resources.

**Comment by matthew-dean** [comment]
I've filed this issue: https://github.com/nwjs/nw.js/issues/3974

**Comment by matthew-dean** [comment]
NEVER MIND. The title bar is controlled elsewhere. Meaning that, for me, the "app" icon always worked, but the "in-app" didn't. The problem was an incorrect path. Derp. See: https://github.com/nwjs/nw.js/wiki/Icons

**Comment by No3x** [comment]
Oops.. Sorry I got this wrong somehow. I found this solution also in my old project so It's likely it was the only way to do it.

**Comment by matthew-dean** [comment]
Np. :-) Regardless, this should probably be documented in detail, as it's not as straightforward as it seems. For instance, the winIco setting should make it clear a) what format it needs to be in, and b) where that icon does and does not apply. It's not intuitive simply from the setting.

**Comment by No3x** [comment]
The option winIco changes the exe icon (shown in the file explorer).
![bildschirmfoto 2015-11-16 um 22 14 55](https://cloud.githubusercontent.com/assets/2690708/11195094/4d5c3b06-8cb0-11e5-975d-a3641216fd69.png)
```
build_dir: './dist',
winIco: './app/app.ico',
// specifiy what to build
mac: false,
```
If you want to change the icon for the taskbar and window icon you have to specify nwjs's `icon`
![bildschirmfoto 2015-11-16 um 22 15 45](https://cloud.githubusercontent.com/assets/2690708/11195102/57b15ff0-8cb0-11e5-9b58-cef402bba2f6.png)

```
{
  ... other stuff here ...
  "window": {
     "icon": "path/to/my/app.png"
  }
}
```
https://github.com/nwjs/nw.js/wiki/Icons
Tested with https://raw.githubusercontent.com/puzzud/gjweb/master/assets/graphics/icons/win/icon.ico

**Comment by adam-lynch** [comment]
Looks like you've resolved this 😄

**Comment by banana618859** [comment]
> What is your operating system (XP, Vista, seven, win8, ...) ?
> Have you any error message in the console output ?
> How did you made your icon file ?
> Does your icon file includes at least the following sizes: 16x16, 32x32, 48x48 ?
> 
> Here a few tutorials to make a valid icon file:
> http://stackoverflow.com/questions/4354617/how-to-make-get-a-multi-size-ico-file
> http://zduck.com/2014/creating-ico-icon-for-windows-app/

first i offer the `icon.png` can not work when nw-builder
finally i offer the `icon.ico` is work
```
var nw = new NwBuilder({
    appName: 'app',
    winIco : './icon.ico', // windows icon
    }）
```
thank you very much!
