### ISSUE TITLE
Subsequent build fails on Win7 x64

### ISSUE THREAD

**Issue by Desmodue** [nwjs/nw-builder#209]
When I build for the first time the folder structure is created and files etc.
Having made some changes to the source and running build again I get an error.

{ [Error: EPERM, mkdir 'q:\getimage\getimage\linux64']
  errno: -4048,
  code: 'EPERM',
  path: 'q:\\getimage\\getimage\\linux64' }

The folder structure is subsequently deleted.
Running a build again then succeeds.

The key part is, this is on a network drive where I keep all by projects. Running this on a local drive there is no issue.
Perhaps a timing\callback issue on the directory preparation ? i.e. the delete if it exists.

**Comment by omaksi** [comment]
I have the same issue on a local drive. If I delete it manually before the build, everything's fine.

**Comment by adam-lynch** [comment]
Is this Linux only or what?

**Comment by Desmodue** [comment]
I was on Win7 x64, usin a mapped drive. Local builds are fine. I was building a Linux .exe though.
Assuming there is some asynchronous stuff going on, if the delete is slow ( network\ slow HD ) then the next step is starting before the delete is complete ?

**Comment by adam-lynch** [comment]
I re-did some of the promises in 2.2.1 so hopefully this is OK. Let me know if it still persists with the latest build.
