### ISSUE TITLE
No canvas after compilation

### ISSUE THREAD

**Issue by chrilith** [nwjs/nw-builder#211]
Hi,

Using a script in the .html file as simple as

```html
<canvas id="cv"></canvas>
<script type="text/javascript">
    var cv = document.getElementById("cv");
    var ctx = cv.getContext("webgl");  // or "2d"
    document.write(ctx);
</script>
```
The script will write "null" with the versioncompiled with
```bash
$ nwbuild ./myApp -p win32
```

No problem running the app in place with -r
```bash
$ nwbuild ./myApp -r
```

Any clue?
Thanks!

**Comment by 1j01** [comment]
Have you kept `ligEGL.dll` and `libEGLESv2.dll` with the compiled exe?
