### ISSUE TITLE
OSX 64 build failed (Reason: image not found)

### ISSUE THREAD

**Issue by crypti** [nwjs/nw-builder#216]
Hi, i'm trying to build app on OS X (Mavericks). 

I made config and builded OS X App, but when i tried to launch it got this error:
Reason: image not found

Another problem i have for Windows build from OS X, i added win to config and now i see:
Fatal error: ENOENT, no such file or directory '/Users/user/Documents/project/public/cache/0.12.0/win64/nw.exe'

**Comment by adam-lynch** [comment]
I think this might be resolved by #337 and version 2.2.1

**Comment by adam-lynch** [comment]
Thanks by the way!
