### ISSUE TITLE
Credits.html is not packaged along with the node-webkit executable

### ISSUE THREAD

**Issue by chasemaupin** [nwjs/nw-builder#225]
I'm not sure if there is a reason behind this but I noticed the list of files for all of the platforms does not include the credits.html file from node-webkit.  Is there a reason why this is not included in order to keep the licensing in place with the packaging?

**Comment by adam-lynch** [comment]
I've never heard of credits.html. If I install NW.js via `nw` (the official npm package), I get this:

![screen shot 2015-05-30 at 12 17 23](https://cloud.githubusercontent.com/assets/1427241/7897060/e84fb87a-06c5-11e5-8ad8-4542cdb20098.png)

Maybe I'm missing something here.

**Comment by chasemaupin** [comment]
Adam,

When I look at the contents in the cache directory I see the credits.html file as part of the node-webkit package that was downloaded.  However, I am using node webkit 0.8.6 (for compatibility with node-hid) so maybe this has been removed in the latest node-webkit?  I don't see it in the nw git repo so that is likely it.
