### ISSUE TITLE
0.13.0-alpha2 unavailable

### ISSUE THREAD

**Issue by merqlove** [nwjs/nw-builder#239]
Hello guys,
Log message said that this version can't be downloaded, but it is available now.

**Comment by sebastialonso** [comment]
:+1:  Available since almost a month, btw

**Comment by adam-lynch** [comment]
node-webkit-builder never supported alpha builds, did it?

**Comment by merqlove** [comment]
@adam-lynch `node-webkit-builder` has checks for alpha in the code:
```js
if(semver.satisfies(version, '>=0.12.0 || ~0.12.0-alpha')) {
   return 'nwjs.app/Contents/MacOS/nwjs';
   return 'node-webkit.app/Contents/MacOS/node-webkit';
 }
```

**Comment by flohdot** [comment]
If you don't specify an option, the latest version will get pulled, though presumably this should only be the case if the version isn't an alpha (as per the changelog). However, right now the "latest" version being identified is 0.12.0-alpha, which fails to download.

**Comment by adam-lynch** [comment]
See #275. Any help would appreciated.

**Comment by adam-lynch** [comment]
Closing in favour of #329. Thanks for reporting.
