### ISSUE TITLE
Error: UNKNOWN, open on build

### ISSUE THREAD

**Issue by dottodot** [nwjs/nw-builder#243]
If I run ```nwbuild myapp -v 0.11.2 -r``` it works fine but if I try to build it using ```nwbuild myapp -v 0.11.2 -p osx64``` I get errors such as

```
[ { [Error: UNKNOWN, open '/myapp/node_modules/grunt-contrib-watch/CONTRIBUTING.md']
    errno: -1,
    code: 'UNKNOWN',
    path: '/myapp/node_modules/grunt-contrib-watch/CONTRIBUTING.md' } ]
```

```
[ { [Error: UNKNOWN, open '/myapp/node_modules/grunt-contrib-uglify/package.json']
    errno: -1,
    code: 'UNKNOWN',
    path: '/myapp/node_modules/grunt-contrib-uglify/package.json' } ]
```
but it references a different file each time I try. Any ideas as to why this would be?

**Comment by dottodot** [comment]
I've just tried on a different machine and don't get this issue. Both are running the same version of nw-builder so unsure what else could be causing this.

**Comment by adam-lynch** [comment]
I have no idea idea to be honest. I've never seen anything like it.

**Comment by adam-lynch** [comment]
Reopen if still an issue please.
