### ISSUE TITLE
How to set a Windows icon when running from console

### ISSUE THREAD

**Issue by julmot** [nwjs/nw-builder#244]
I am running nw-builder under the Windows console with `nwbuild ./`. However, I see there is an option object when using it as a module, but this options aren't available in the console. How can I set the .exe-icon when running from console?

**Comment by adam-lynch** [comment]
I've never used it but judging by [this line](https://github.com/mllrsohn/nw-builder/blob/6095b01e9726cc186adef58336007fb5a39fdba3/bin/nwbuild#L68) it looks like it should work. Have you tried passing `--winIco`?

**Comment by julmot** [comment]
I didn't because it is not in the documentation. However I'll try it and post it here...

**Comment by julmot** [comment]
An error occured with errno -4043

**Comment by julmot** [comment]
This seems to work!
