### ISSUE TITLE
error when running app on linux64

### ISSUE THREAD

**Issue by stkevintan** [nwjs/nw-builder#246]
here is my code:
```Javascript
gulp.task('release', ['default'], function (cb) {
    var nw = new NwBuilder({
        files: './*', // use the glob format
        platforms: ['linux64']
    });

    nw.on('log', console.log);
    nw.build(function (err) {
        err && console.log(err);
        cb(err);
    });
});
```
there is no error found during buiding,but when running the app ,I got following error:
```
Uncaught ReferenceError: require is not defined
Not allowed to load local resource: 
file:///tmp/kevin/.org.chromium.Chromium.FaDW8G/dist/index.html
```

**Comment by adam-lynch** [comment]
That's typically not a problem with nw-builder. Maybe try reduce your app to something simpler and you should be able to find the problem.

**Comment by stkevintan** [comment]
@adam-lynch   It's my fault,I should use `./**` instead of `./*` for recursively matching files.  
Sorry for my stupid mistake.

**Comment by adam-lynch** [comment]
No problem :smile:
