### ISSUE TITLE
OSX build fails

### ISSUE THREAD

**Issue by gera2ld** [nwjs/nw-builder#247]
OSX built application always show `nw:blank` and seems not to run the main script.

This is part of my script:
``` js
var NwBuilder = require('nw-builder');
new NwBuilder({
  files: 'app/**',
  platforms: ['osx']
});
```

There is a `package.json` in `app/` and the `main` URL is set correctly. It works when I run from the terminal and specify the `app/` path. It works if I copy the `app/` folder to `path/to/Resource/app.nw/` manually (Thanks to the nw.js document).
I'm wondering if I have missed something or it's designed in purpose?

**Comment by adam-lynch** [comment]
Hmm. Maybe the glob isn't working. Try `./app/**`?

**Comment by gera2ld** [comment]
I think I've found the problem. Actually I was trying to build for both `win` and `osx` platforms, and when a `winIco` is given, the procedure fails on:

> Error while updating the Windows icon. Wine (winehq.org) must be installed to add custom icons from Mac and Linux.

Then the procedure seems to be halted (I prefer it not though). If `winIco` is removed the `osx` part works too.

BTW, `app/**` and `./app/**` both works. Thanks anyway.

**Comment by adam-lynch** [comment]
> BTW, `app/**` and `./app/**` both works. Thanks anyway.

Yeah, it usually does... *usually*. I've seen issues on Windows :smile:
