### ISSUE TITLE
create release for win32 platform failed on ffmpegsumo.dll missing error 

### ISSUE THREAD

**Issue by cj179john** [nwjs/nw-builder#252]
I got this error when I run nw-builder in grunt:
Running "nwjs:src" (nwjs) task
Latest Version: v0.13.0-alpha3
Using v0.13.0-alpha3
Create cache folder in /app/cache/0.13.0-alpha3
Downloading: http://dl.nwjs.io/v0.13.0-alpha3/nwjs-v0.13.0-alpha3-win-ia32.zip
  downloading [====================] 100% 0.0s

Create release folder in /app/release/Collector/win32
Fatal error: ENOENT, no such file or directory '/app/cache/0.13.0-alpha3/win32/ffmpegsumo.dll'

It was working with v0.12

Can anyone help with this?

**Comment by ant-fx** [comment]
same here

**Comment by ant-fx** [comment]
Appears to be affecting v0.13 only, forcing to v0.12 works:

nwbuild -p win32 -v 0.12.0 -o "../" -f ./

**Comment by kessiler** [comment]
I have the same problem.
It's work using the command above. But isn't a better solution.
Thanks @ant-fx

**Comment by cj179john** [comment]
How to run this command in Grunt?

**Comment by kessiler** [comment]
@cj179john You can define the version to be used on your task.
See the example below:

grunt.initConfig({
		pkg: grunt.file.readJSON('./package.json'),
		nwjs: {
			options: {
				platforms: ['win'],
				buildDir: './builds',
				**version: 'v0.12.0'**
			},
			src: ['./index.js']
		}
	});

**Comment by plcstpierre** [comment]
Could nw-builder use the same version specified in package.json?

**Comment by kessiler** [comment]
@plcstpierre I think isn't good, because the version used in package.json normally is your app's version.

**Comment by plcstpierre** [comment]
I mean using the version of nw specified in the package.json

I got the same problem and I realized that nw-builder was using the 0.13.x version (and I developed my stuf on 0.12.x). Any reason why using an arbitrary version? I would expect that my software will be packaged on the same versionthat  I have developed my stuff. If it was not of this bug, I would not have realized that another version was used.

**Comment by bastimeyer** [comment]
@plcstpierre 
The default version being used is the "latest" ([see here](https://github.com/nwjs/nw-builder#optionsversion)). I think this should be changed to exclude pre-releases, so it doesn't break things.

Btw, the v0.13.x alphas don't work because of the new build structure and the missing archive content specifications [here](https://github.com/nwjs/nw-builder/blob/master/lib/platforms.js).

**Comment by medozas** [comment]
Is there some ETA expected for the archive content to be adapted for build? Just curious, since I would like to start off trying the new engine without much hassle (which nw-builder is made for, right?) ;)

**Comment by adam-lynch** [comment]
This has sorted since the issue was created I think. Correct me if I'm wrong.

**Comment by ruffrey** [comment]
I am still experiencing this issue as of today, nw-builder@2.1.0 and grunt-nw-builder@2.0.0

```
Running "nwjs:src" (nwjs) task
Latest Version: v0.13.0-alpha6
Using v0.13.0-alpha6
Create cache folder in /Users/jeffparrish/nodewebkit-cache/0.13.0-alpha6
Downloading: http://dl.nwjs.io/v0.13.0-alpha6/nwjs-v0.13.0-alpha6-win-ia32.zip
Create cache folder in /Users/jeffparrish/nodewebkit-cache/0.13.0-alpha6
Using cache for: osx64
Create cache folder in /Users/jeffparrish/nodewebkit-cache/0.13.0-alpha6
Downloading: http://dl.nwjs.io/v0.13.0-alpha6/nwjs-v0.13.0-alpha6-linux-x64.tar.gz
  downloading [====================] 100% 0.0s

Create release folder in /Users/jeffparrish/apollo/public/release/Apollo/win32
Create release folder in /Users/jeffparrish/apollo/public/release/Apollo/linux64
Create release folder in /Users/jeffparrish/apollo/public/release/Apollo/osx64
Fatal error: ENOENT, no such file or directory '/Users/jeffparrish/nodewebkit-cache/0.13.0-alpha6/win32/ffmpegsumo.dll'
```

**Comment by medozas** [comment]
same here.

**Comment by adam-lynch** [comment]
@ruffrey alpha builds aren't really supported right now. It's kinda a bug that it's using v0.13.0-alpha6. So to fix this just specify a version (`0.12.2` for example) in the nw-builder options.

If you do actually want to use alpha builds, then see #275.

@medozas does that apply to you too?

**Comment by medozas** [comment]
@adam-lynch: well sure, I think we do understand that alpha is not supported, and for the moment the fixed version specification is clear, yet it would be great to be able to check out new alpha, and since nw-builder simplifies the bundling a bit it would have been great to check it out directly... ;)

**Comment by dragonjet** [comment]
still getting this even with 0.13 not in alpha anymore. hope this gets fixed soon. I need the chrome APIs so I can't resort to 0.12

**Comment by laduran** [comment]
I am experiencing this problem. But I am trying to use the 0.13.beta5 of NWJS. It seems like the nw-build is using manifest files from 0.12? But I don't know how to fix.

**Comment by keiserS** [comment]
Same problem here with 0.13.beta5 of NWJS on Win platform. Actually I'm using gulp to make build. I really don't know what I'm doing ATM, as trying to test some things started from today :). Above mentioned grunt config I haven't tested yet (where is that config found?). As far I have figured out gulp has its own gulpFile.js which I tried to modify with above mentioned command "-v 0.12.0"

// Run project
gulp.task('run', shell.task([
    'node node_modules/nw-builder/bin/nwbuild  -r ./'
]));
.....
var nw = new NodeWebkitBuilder({
        files: ['./package.json', './app/**/*'].concat(modules),
        cacheDir: './build/cache',
        platforms: platforms,
        macIcns: './app/assets/icons/play-icon.icns',
        winIco: './app/assets/icons/play-icon.ico',
        checkVersions: false,
        version: '0.12.3'  
    })
--------------
So after some searching added different version for build... download of proper version started, but...
now I'm getting some strange error about Anolis.Resourcer (DibException : Unrecognised BitmapInfoHeader dwSize).

I hope this will help further with build version switch to someone.

K.

P.S. if someone is familiar with my problem pls drop me a note, tnx

**Comment by larssb** [comment]
Hi there...still happens for v0.13.beta6 - but yes sure works when just using latest 0.12 ver.

**Comment by larssb** [comment]
Hi again.....I can live with just specifying -v 0.12.3 - maybe I'm just misunderstanding something. Just thought it should by using the newest one.

**Comment by keiserS** [comment]
with new nw release, build is not successful, at least I'm not able to build it. With 0.12.3 version it builds at least but then again, after build (and above issue with winIcon definition being omitted) I'm getting whole bunch of missing js modules, that for some reason need to be included to dependency list.
I have used example from this URL: http://thejackalofjavascript.com/node-webkit-webrtc-and-angularjs-a-video-chat-client/ which seemed to be working on older version. Any help with this would be appreciated.

K.

**Comment by natcohen** [comment]
@adam-lynch I think you should reopen this issue... nw.js 0.13 is now in beta and it would really make sense to fix this especially because nw.js 0.13 documentation redirect to this tool!

**Comment by medozas** [comment]
@adam-lynch +1 for @natcohen

**Comment by aysark** [comment]
Facing this issue and it basically makes this great module unusable for me.  As when i build for v0.12.* i am missing various js files it seems, my app is broken essentially.  jQuery is missing for some reason in the built app.  Tried v0.13.0-beta7 and it fails with lstat missing.

**Comment by adam-lynch** [comment]
@natcohen @medozas you mean it's out of beta yeah?

**Comment by adam-lynch** [comment]
@natcohen @medozas nevermind, I'm wrong. Since it's still in beta, #275 is what's blocking it.

**Comment by andrewvarga** [comment]
This seems to be a problem when I try to use 0.14.0 which was just released. Any ideas what I could do?

**Comment by philweigeomatics** [comment]
really whats going on, can someone help on finding a solution. I use mac to build a windows exe with nw builder on version 0.14.2 but same problem appears no matter if its for win32 or 64. But works with OSX

**Comment by sourceskyboxer** [comment]
Hello guys, same problem here :(

I can not understand why does nw-builder throws error message like this Windows 7 Pro x64, 8, 10 same

Who has Ubuntu and has same problem? I think better We need use manual copy from nw.js website and win32, win64, linux32, linux64, mac32 and mac64. nw-builder can not work because it doesn't recognize to dos of Windows, Linux and Mac are same Unix and they have conflict of file system.

Please improve file system recognition 

Example ApplicationStorageDirectory or get env-function "%AppData%\Roaming" like this C:\Users\<Username>\AppData\Roaming for Windows 7, 8 and 10

And for Linux like this /home/<username>/.libraries
For Mac OS X: /VolumeName/Users/<username>/Library/Application Supports/ ( I don't know that sorry I have not Mac OS X Computer...

Thanks for improvement - if you build js with "fs" and "system" ( I don't know - If i remember "system" of node.js can use "get_env" like C++/Header because it is better to manage if nw-builder can downlaod and can "copy fresh" without stupid error messages....

Thanks!

**Comment by evshiron** [comment]
@sourceskyboxer You are asking the most frequently asked question recently. Please refer to #296 for 0.13.x/0.14.x support and please take a look at [evshiron/nwjs-builder](https://github.com/evshiron/nwjs-builder) if you interested.

**Comment by GabrielTK** [comment]
The problem continues in 0.15.1

**Comment by GRIM2D** [comment]
The probem continuses in 0.15.2 in on OSX targetted win32, win64

**Comment by heyitskippy** [comment]
for 0.15.2 and win32 in `nw-builder\lib\platforms.js` replace with
```javascript
win32: {
        needsZip: true,
        getRunnable: function() { return 'nw.exe'; },
        files: { // First file must be the executable
            '<=0.9.2': ['nw.exe', 'ffmpegsumo.dll', 'icudt.dll', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak'],
            '>0.9.2 <0.12.0': ['nw.exe', 'ffmpegsumo.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak', 'locales'],
            '>=0.12.0 <0.15.3': ['nw.exe', 'ffmpegsumo.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak', 'locales', 'd3dcompiler_47.dll', 'pdf.dll'],
            '=0.15.3': ['nw.exe', 'ffmpeg.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'locales', 'd3dcompiler_47.dll', 'natives_blob.bin', 'node.dll', 'nw.dll', 'nw_100_percent.pak','nw_200_percent.pak', 'nw_material_100_percent.pak', 'nw_material_200_percent.pak', 'resources.pak','snapshot_blob.bin','nw_elf.dll']
        },
        versionNameTemplate: 'v${ version }/${ name }-v${ version }-win-ia32.zip'
    },
```

**Comment by adam-lynch** [comment]
Newer versions are now supported as of 2.2.1

**Comment by akvallejos** [comment]
I use OSX to build NW.JS executables, and I am still stuck on using -v 0.12.2. Trying any later version throws
>{ [Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/nw->builder/cache/0.16.0/win32/ffmpegsumo.dll']
 > errno: 34,
 > code: 'ENOENT',
 > path: '/usr/local/lib/node_modules/nw-builder/cache/0.16.0/win32/ffmpegsumo.dll',
 > syscall: 'lstat' }`

OSX builds just fine, but I cannot build Windows executables.

**Comment by DblK** [comment]
Are you sure you use the latest version?
I saw in your error the folder `cache/0.16.0/` instead of `cache/0.16.0-sdk` or `cache/0.16.0-normal` since version `3.1.0` which implement flavors.

Can you update to the latest version and provide me feedback?

**Comment by akvallejos** [comment]
Needed to update Node.js... ha! Thanks for the assist, it's all good now.

**Comment by saravanans-arch** [comment]
Still this problem continue in windows,
AppData\\Roaming\\npm\\node_modules\\node-webkit-builder\\cache\\**0.25.2**\\win32\\ffmpegsumo.dll'
Any one can assist me?
