### ISSUE TITLE
Unable to download nodewebkit.

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [nwjs/nw-builder#253]
I thought this was fixed in #127 but i'm still getting this issue 

<pre><code>
Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-win-x64.zip
undefined
Unable to download nodewebkit.
</code></pre>

**Comment by AgenceUzik** [comment]
We're having the same issue using nw-builder v.2.0.2. We'd need a solution quickly, and would really appreciate any help.

**Comment by Karlheinzniebuhr** [comment]
@AgenceUzik you can try this, it worked for me https://github.com/jyapayne/Web2Executable

**Comment by AgenceUzik** [comment]
Thanks you for the link. It Web2Executable actually works, but binaries are 2 GB each, instead of circa 120 MB… I'll try to find another way to build the app.

**Comment by Karlheinzniebuhr** [comment]
Did you try to compress them with 7zip ? It reduces the size by 70% in my case

**Comment by AgenceUzik** [comment]
Yes, but actually, I could not use a zipped version.

I solved the problem by downgrading nwjs to version 0.12.4 (and not 0.13.0 alpha-3 which is used by default).

**Comment by adam-lynch** [comment]
See #275. Any help would appreciated.

**Comment by adam-lynch** [comment]
Closing in favour of #329. Thanks for reporting.
