### ISSUE TITLE
0.13.0-alpha3 linux64 build fails

### ISSUE THREAD

**Issue by DamonGant** [nwjs/nw-builder#254]
Building "latest" on linux64 fails because the archive does not contain a "nw.pak"

**Comment by c0n5pir4cy** [comment]
They've changed the nw.pak in the archive to nw_100_percent.pak; renaming that to nw.pak brings up a bunch of other errors about missing static libraries.

Looks like nw.js might be moving to a structure where all of the resources are in the pak files in the new version. Right now I've just forced the use of an older version.

**Comment by bmsrox** [comment]
How did you solve it ?

**Comment by c0n5pir4cy** [comment]
Hey @bmsrox 

I didn't really fix it, I just passed in the version option to use an older version of nw.js for my linux build option.

**Comment by Belenn88** [comment]
Hey @c0n5pir4cy  which version did you use?
my config:
var nw = new NwBuilder({
        version: ' ? ',
        files: './Player/**',
        platforms: ['win64'],
        currentPlatform: 'linux64',
        winIco: './icons/icon.ico'
    });
Thank you!

**Comment by c0n5pir4cy** [comment]
Hey @Belenn88 

I can't remember what I used as it was a while ago, but try '0.12.3' or 'v0.12.3' as that is the latest version which seems to use an ordinary structure.

**Comment by Belenn88** [comment]
Thank you! @c0n5pir4cy

**Comment by adam-lynch** [comment]
See #275. Any help would appreciated.

**Comment by petarov** [comment]
Bump! Linux builds still fail with:

`
Fatal error: ENOENT: no such file or directory, lstat '/<path>/cache/0.13.4/linux64/nw.pak'
`

I tested 0.13, 0.14, 0.15. Only 0.12 seems to work.

**Comment by petarov** [comment]
@evshiron ah, I see. Thanks for the info 🍺

**Comment by adam-lynch** [comment]
Closing in favour of #329. Thanks for reporting.
