### ISSUE TITLE
It has been a long time

### ISSUE THREAD

**Issue by helloncanella** [nwjs/nw-builder#255]
I'm trying to use nw-builder following the steps given in the home page of reposit (*nwbuild -r  myapp*),
but it has been more than one hour and nothing happens. The unique information the I've received from the terminal is *Lauching your app*

What could be the problem?

I appreciate any help.

**Comment by raitucarp** [comment]
+1

**Comment by tkang007** [comment]
In my case, it was related with company proxy issue during dowloading nwjs.
After setting cntlm auth for not using plaintext password, it was sold. Or,
you can prepare it at cache directory by manual downloading and decopress
at cache/version/platform directory. Hope helpful.

**Comment by adam-lynch** [comment]
Have you specified a version of nwjs in the config?

**Comment by adam-lynch** [comment]
This is probably related to #275. Any help would appreciated.
