### ISSUE TITLE
Writing to new file after build on Linux

### ISSUE THREAD

**Issue by brian-mann** [nwjs/nw-builder#258]
I noticed that my app becomes a giant zip file in Linux. The problem is when my app is running it tries to write to relative files. This works, but once the app restarts, this file is never persisted.

I'm confused as to how this file is able to be written in the first place. Node is able to `fs.read` into any file in the archive (without unzipping) but newly created files are not actually added to the archive.  I have no idea how it's able to write and then read back from the "temporary files" that disappear after the app is closed.

Any insight / suggestions? In OSX this isn't a problem due to the unzipped folder structure of a `.app` file.

**Comment by brian-mann** [comment]
Okay I see now that `nw` will unpack the `.zip` into a `tmp` directory in the OS. That is why it would work when I ran it but those files would not be persisted on the next run.

The #200 PR fixed this for me by no longer zipping the build.

**Comment by adam-lynch** [comment]
Ok so... this should be sorted by #193 too
