### ISSUE TITLE
options.version should handle range

### ISSUE THREAD

**Issue by plcstpierre** [nwjs/nw-builder#261]
nw-builder should be able to handle version like npm

I cannot specifies a caret or tilde in the version number.

**Comment by plcstpierre** [comment]
A the moment the following message is displayed

The version ^0.12.3 is not valid.

**Comment by kyle-ilantzis** [comment]
I think I understand the problem

https://github.com/nwjs/nw-builder/blob/6095b01e9726cc186adef58336007fb5a39fdba3/lib/index.js#L180

Function checkVersion uses semver.valid which behaves like so

![semver-valid](https://cloud.githubusercontent.com/assets/5513243/10297870/6515eab0-6ba6-11e5-9962-6654b921b91e.PNG)

But checkVersion should use something like

semver.maxSatisfying(versions, range): Return the highest version in the list that satisfies the range, or null if none of them do.

**Comment by kyle-ilantzis** [comment]
Here is a snippet using semver.maxSatisfying and NwVersions.getVersions

https://gist.github.com/kyle-ilantzis/763dd81f085e476ef504

**Comment by adam-lynch** [comment]
I personally wouldn't use the caret as I wouldn't have faith in nwjs automatically being updated for my app I'm about to put into production. I can see how someone might use it though. How about a pull-request? :smile:

**Comment by kyle-ilantzis** [comment]
A pull request sounds like a good idea, ill get on it.
