### ISSUE TITLE
CORS issue: can't load local resources with ajax request

### ISSUE THREAD

**Issue by yoderjen** [nwjs/nw-builder#265]
The ajax get requests in my code are failing.  I think it is because Chrome considers file:// requests to be cross-domain and disallows them.  How can I work around this?  

I tried adding "chromium-args": "--allow-file-access-from-files"  to my package.json file, but it didn't solve the problem.

**Comment by adam-lynch** [comment]
This is an issue for the [NW.js Google group](https://groups.google.com/forum/#!forum/nwjs-general), not this module. Thanks.
