### ISSUE TITLE
Allow plain bundling of files without creating app.nw for all platforms

### ISSUE THREAD

**Issue by CxRes** [nwjs/nw-builder#266]
Roger recommends not to zip files for large programs. To enable this please allow bundling without zipping and merging on windows and linux platforms as well.

**Comment by adam-lynch** [comment]
This will be sorted by #193

**Comment by matthew-dean** [comment]
@CxRes See https://github.com/nwjs/nw-builder/pull/200. #193 does not address this but there are pull requests in #200 that do.

**Comment by adam-lynch** [comment]
#200 merged, 2.2.0 released. Thanks.

**Comment by CxRes** [comment]
Nice!!! Thanks!
