### ISSUE TITLE
OSX application packaged to pkg, installs a broken application

### ISSUE THREAD

**Issue by drown-zed** [nwjs/nw-builder#267]
If node webkit application is built on osx, and then packaged to pkg - the installed app is broken. If the app is built using windows (same version 0.12.3), everything can be packaged just fine.
Any ideas why this is happening?

**Comment by adam-lynch** [comment]
>If node webkit application is built on osx, and then packaged to pkg - the installed app is broken. 

Built for Mac or Windows?

**Comment by hudichao** [comment]
@drown-zed Have your solved this? I had the same problem now...

**Comment by Mior** [comment]
I know this is off topic but @drown-zed how are you packaging application into pkg?

**Comment by drown-zed** [comment]
Sorry about not replying, the problem still exists. 

> Built for Mac or Windows?

Built for mac on mac
