### ISSUE TITLE
nwbuild hangs at "Launching App"

### ISSUE THREAD

**Issue by husterk** [nwjs/nw-builder#272]
I am testing out nw-builder on a Windows 7 machine using a pretty simple setup (see below). I am running "nwbuild" as an npm script via `nwbuild -r \"./src\"`. However, each time I execute this script the nw-builder tool re-downloads the NW.exe app (even though it already exists in the cache directory) and then hangs on the "Launching App" message. I am able to see that "nw.exe" is running in the background via the Windows Task Manager but I do not see any activity from it. Any help would be greatly appreciated.

package.json
```
{
	"name": "SampleApp",
	"version": "0.0.1",
	"main": "index.html",
	"window": {
		"toolbar": false,
		"width": 1024,
		"height": 768,
		"show": true,
		"frame": true,
		"resizable": true
	}
}
```

Also, it should be noted that subsequent downloads of the NW.exe app are placed one directory too deep (see example below).

First Download:
`node_modules/nw-builder/cache/<version>/<platform>/[extracted-files]`

Subsequent Downloads:
`node_modules/nw-builder/cache/<version>/<platform>/<nwjs-version-platform>/[extracted-files]`

**Comment by husterk** [comment]
Update: I pointed nw-builder to nw.js v0.11.6 instead of latest and everything started working. It seems that all of the builds based on io.js (not node.js) are failing on my windows machine.

**Comment by adam-lynch** [comment]
Could you try running your app with the `nw` module and see what happens?

**Comment by alicona** [comment]
Mine was downloading the alpha build, I pointed it to 0.12.3  and it worked.

nwbuild -v 0.12.3 -r /path/to/app/

**Comment by iurimattos** [comment]
try 
nwbuild -v 0.12.3 -r /path/to/app/ 
here it works!!

**Comment by mariowise** [comment]
I dont think the `-r` option is valid for this question. The idea is to build a `.exe` not to run the app. I've the same problem and it does not work, even with the `v0.11.6` version.

I'm trying to build the `win64` version from my `osx`. Is that even posible? I've tried with all of these commands and the resulting `.exe` just creates some processes in Windows and nothing happens.

	$ nwbuild -p win86 -v 0.12.3 .
	$ nwbuild -p win32 -v 0.12.3 .
	$ nwbuild -p win32 -v 0.12.3 .
	$ nwbuild -p win64 -v 0.11.6 .
	$ nwbuild -p win64 -v 0.11.6 -r .
	$ nwbuild -p win64 -v 0.11.6 -r . -o ./build

**any help will be greatly appreciated.**

**Comment by mariowise** [comment]
Update: Well It happens to be my old Windows machine. I created a virtual machine with a brand new Windows and the resulting `.exe` worked with no problems. I'm using the `0.12.3` version of nw.js

**Comment by adam-lynch** [comment]
This could've been related to alpha builds like mentioned above. Should be ok as of version 2.2.1.
