### ISSUE TITLE
Unpacking application into custom folder

### ISSUE THREAD

**Issue by Mior** [nwjs/nw-builder#273]
We have created nw application which persist data in local sqlite database.

Problem when using nw-builder is that once user run's application it will create new temp directory. Every change is persisted to local db in this temp folder, but when user open application again different temp directory is created and changes from from db are lost. (in different unknown temp folder)

Is it possible to tell nw-builder when unpacking to use custom directory? Or at least same temp everytime?
Why is it using temp in first place? Couldn't it just unpack needed files in current dir?

Thanks for any info.

**Comment by theRaja** [comment]
Facing the same issue - is there any workaround?
Appreciate any help

**Comment by Mior** [comment]
@theRaja It seems its not issue of nw-builder but nw.js itself see https://github.com/nwjs/nw.js/issues/815. When nw.js dealing with packed app.nw or even bundled together with nw.exe it is unpacking it into temp folder by default and I was not able to find any option to override this default behavior.

We were able to come up with 2 workarounds.
 1. embed your local db file along with nw.exe not inside of your app.nw nor bundled in nw.exe itself. Than you are able to point your code into that db file using executable location described here: https://github.com/nwjs/nw.js/issues/1197 . This still create temp folder but your db is in different place so you don't lose persisted data.
* One downside is that it take some time to start application as it always unpacking application into temp folder. (depending on size of your application).

 2. Pack you application in different manner as mentioned here https://github.com/nwjs/nw.js/issues/815 . Meaning pack your application files along with nw's nw.exe (package.json need to be in same folder as nw.exe). nw.exe will just open package.json and thus your application as is in same folder every time. 
* Benefit same as before, db is always in same place. Also bootstrap of your application is really quick compare to 1. as it doesn't need to unpack your application into temp folder.
* Downside is that all your code is visible right next to executable file.

Hope this helps and also if you come up with way how to overcome this nw.js default behavior, let me know.

**Comment by adam-lynch** [comment]
I agree that this is not an issue with nw-builder.
