### ISSUE TITLE
Be smarter about available versions (& support alpha builds)

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw-builder#275]
Depends on https://github.com/nwjs/nw.js/issues/4037.

This module would then get and validate versions a lot more solidly.

- All versions would be grabbed reliably.
- It would be a lot easier to avoid alpha builds when the version option is defaulted to `latest`.
- Changes to the platform ZIPs between versions won't break anything.
- People could use alpha builds if they like.
- If the user tries to build for a version which doesn't support that platform, an error will be thrown.

Fixes #239, #253, #254, (probably) #255, #259, #262, and probably more.

**Comment by gaving** [comment]
A big :+1: for this from somebody constantly working off alpha builds!

**Comment by mib4fun** [comment]
update ?  nwjs/nw.js#4037 is kinda fix now, right ?

**Comment by adam-lynch** [comment]
Closed as of 2.2.1 (#337)
