### ISSUE TITLE
Fatal error: path must be a string

### ISSUE THREAD

**Issue by sven-codeculture** [nwjs/nw-builder#278]
When i try to Build an app with v2.2.0 i get an TypeError: path must be a string.
Version 2.1.0 still works fine for me.

Greetings Sven

**Comment by rleemorlang** [comment]
I'm seeing the same problem.

Note that after downgrading if you see an error like:

```
Fatal error: ENOENT: no such file or directory, lstat '/some/path/to/a/cache/0.11.6/win32/nw.exe'
```

Then delete the referenced cache directory and re-run.

**Comment by Forecaster** [comment]
Version 2.2 of what? I'm getting this as well and I don't know what to downgrade. Using nw-builder 1.0.8.

**Comment by Jetsly** [comment]
I'm seeing the same problem.  when build with osx32 platform
when build only win32 platform, works fine for me

**Comment by Forecaster** [comment]
Unfortunately that's not very useful to me. I need a way to build for linux and OSX...

**Comment by sven-codeculture** [comment]
NW-Builder v2.1.0 works file. Just install it with npm install nw-builder@2.1.0

**Comment by MIKUScallion** [comment]
NW-Builder v2.1.0 works fine, please do no use the 2.2.0, it kill my many time but don't fine.

**Comment by adam-lynch** [comment]
This should fine now. Try the latest version. Thanks for reporting.
