### ISSUE TITLE
Exclude npm dev-dependencies

### ISSUE THREAD

**Issue by snuggles08** [nwjs/nw-builder#280]
I have nw-builder as a dev dependency and it's being included in the app, bloating it. Could there be an option to exclude it?

**Comment by adam-lynch** [comment]
@snuggles08 see the `files` option https://github.com/nwjs/nw-builder#optionsfiles-required;

>The path to your node webkit app. It supports simple-glob so you can do stuff like ['foo/*.js', '!foo/bar.js', 'foo/bar.js'].

`!foo/bar.js` excludes `foo/bar.js`.
