### ISSUE TITLE
Build with windows OS: TypeError: path must be a string & Icon issue. (V2.2.0)

### ISSUE THREAD

**Issue by landpy** [nwjs/nw-builder#284]
When I build the nw app with v2.2.0(v2.1.0 works fine) there is a "TypeError: path must be a string" issue occurs, the build configuration is as following:
var NwBuilder = require('nw-builder');
var nw = new NwBuilder({
    files: './src/*', // use the glob format 
    platforms: ['osx32', 'osx64', 'win32', 'win64'],
    version: "0.12.3",
    appName: "landpy",
    appVersion: "0.0.0.1",
    buildType: "versioned",
    winIco: "launch.ico"
});

//Log stuff you want

nw.on('log', console.log);

// Build returns a promise
nw.build().then(function () {
    console.log('Done!');
}).catch(function (error) {
    console.error('Error: '+error);
});

And I found that the "winIco" value of options is only effective with small icon, if you change to "Medium Ico"+, the exe file will show the NW build-in icon.

**Comment by landpy** [comment]
The ico issue is not the NW.js issue. When I resize the the ico sometimes it display as nw.js defualt icon. So I think when I generate the ico I should generate all the size ico, maybe I miss some size.

**Comment by anhvu980** [comment]
I also faced this error when building by v2.2.0. Didn't try with v2.1.0 yet.

**Comment by dariuszsikorski** [comment]
Joining the issue.

build.js code:

```
var NwBuilder = require('nw-builder');
var nw = new NwBuilder({
    files: './app-source/**/**', // use the glob format
    platforms: ['osx32', 'osx64', 'win32', 'win64'],
    version: '0.12.3'
});

//Log stuff you want

nw.on('log',  console.log);

// Build returns a promise
nw.build().then(function () {
   console.log('all done!');
}).catch(function (error) {
    console.error(error);
});
```

**Comment by qluqua** [comment]
@dariuszsikorski thank you mate, your solution helped me to solve same problem. i just added `zip: false` to NwBuilder settings and it works now.

**Comment by wloske** [comment]
On the Mac this does not solve the issue. I am using `zip: false` but still receive an error saying
```
WARNING!!
macZip is deprecated. Use the zip option instead.
```

in addition to the 
```
Fatal error: path must be a string
```

Falling back to nw-builer@2.1.0 helps ...

**Comment by adam-lynch** [comment]
Fixed today. Please try the latest version. Thanks.
