### ISSUE TITLE
Support beta

### ISSUE THREAD

**Issue by Sytten** [nwjs/nw-builder#285]
Hi,

I would like to know if you will support the beta release of NWJS, because currently I get all sorts of errors when I try to build with the version 0.13.0...

Thanks!

**Comment by kucix** [comment]
+1

**Comment by janviehweger** [comment]
+1

**Comment by janviehweger** [comment]
this should work:
`nwbuild -r -v 0.13.0-beta6 .`
it pulls the files from http://dl.nwjs.io/v0.13.0-beta6/. 
the problem is, that you only get what they call the "normal" version - no "sdk" or "nacl".
should be not that difficult to hack the scrapePtrn in nw-builder/lib/versions.js

**Comment by gitawego** [comment]
yeah. hope the build flavors option could be supported soon

**Comment by Sytten** [comment]
I will check to modify my script, I forked an app that use gulp with a coffeescript script, I guess I will have to rewrite it (anyway who the f*ck use coffeescript)

**Comment by gitawego** [comment]
@Sytten for your convenience ^^ http://js2.coffee/

**Comment by Sytten** [comment]
Thanks! Still I cant build my app with the beta, nwbuilder needs a proper update. Meanwhile I will continue to use 0.12.3...

**Comment by adam-lynch** [comment]
Closing since we already have #275. I'd love any help I could get :+1:
