### ISSUE TITLE
Autoinstall modules when running the build

### ISSUE THREAD

**Issue by himanshu1691** [nwjs/nw-builder#287]
I created builds for various platforms using the builder but the file size is close to 200MB.
Is it possible to create a build that downloads the required dependencies from the internet when run by the user.

**Comment by adam-lynch** [comment]
This is not a problem with nw-builder so I'll close this. 

What I think you can do is create an installer for your app (which doesn't contain your app and therefore will be really lightweight) which when ran, goes and downloads the required files. I haven't done this myself but I know it's possible, but not with nw-builder.
