### ISSUE TITLE
nwbuilder looking for ffmpegsumo.dll

### ISSUE THREAD

**Issue by CxRes** [nwjs/nw-builder#290]
ffmpegsumo.dll was removed from newer chrome. nwbuild seems to expects that all versions of NW.js, including the latest beta has this file in the same spot. Please update!

**Comment by Aleksey-Danchin** [comment]
This problem too. Ubuntu 15.04

```
{ [Error: ENOENT: no such file or directory, lstat '/home/old/Desktop/tork/cache/0.13.0-beta7/win64/ffmpegsumo.dll']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/old/Desktop/tork/cache/0.13.0-beta7/win64/ffmpegsumo.dll' }
```

**Comment by tomlandia** [comment]
PR #281 fixes this and has been around for 2 months 😫.

**Comment by adam-lynch** [comment]
@CxRes beta builds are currently not supported properly, see #275.

**Comment by CxRes** [comment]
@adam-lynch But nwjs is now RC??? I don't mind waiting just that would like to be on the same page as to what to expect...

**Comment by adam-lynch** [comment]
@CxRes yeah, currently you can't use an RC version. Any help on #275 is welcome.
