### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by Satish102** [nwjs/nw-builder#291]
I have built the package using -o and -v options and build got create successfully for all platforms. However, when I click on the exe created by my project name is opening NW.exe instead of my application. Any quick help really appreciated.

Thanks in advance

Satish

**Comment by nofear87** [comment]
Same here!

**Comment by Satish102** [comment]
Unfortunately there are no replies and we may have to look at different library.

**Comment by MrHalfman** [comment]
Did anyone managed to solve this problem?

I noticed that the executable works on the computer that built it but it shows the default NW.exe page on others computers. (Maybe an absolute path is set somewhere?)

**Comment by adam-lynch** [comment]
@Satish102 Could you show me the command you're using in full?

**Comment by NicolasNeubauer** [comment]
Same here.
I use the skeleton generated by https://github.com/christiannwamba/generator-wean
Found I first need to add icons, but that's fine.
Then ran into that exact issue with the provided grunt build task
Started using nw-builder directly

I do > node node_modules\nw-builder\bin\nwbuild -p win64 -v 0.12.3 . 
(there's also an issue with the cli under Windows 10(?) so I don't have a nw-build.cmd (could be me doing something wrong, though), plus, I want to add some debug output, so pointing to a local version of nw-builder and starting it via node directly)
(there's also an issue where 0.13-rc3 seems to come without 'ffmpegsumo.dll', triggering a new download every time, so I force v 0.12.3)

I get build/[project_name]/win64/[project_name].exe
When I run it, I get the nwjs startup page.
Similarly for win32.

Just switched from node 4.4 to node 5.9 but that didn't change things either.

The same works on Mac OS.

**Comment by NicolasNeubauer** [comment]
Well it turns out after not only installing node 5.9, but also deleting node_modules/*, uninstalling nw-build and reinstalling everything, it actually works for me.
