### ISSUE TITLE
Unable to download nodewebkit

### ISSUE THREAD

**Issue by accessibleweb** [nwjs/nw-builder#293]
Hi,
Got this error using 0.12.3,
Using v0.12.3
Create cache folder in D:\XXX\cache\0.12.3
Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-win-x64.zip
undefined
Unable to download nodewebkit.

Try to set anoher version of node webkit but got same problem.
Thanks for your help.

**Comment by adam-lynch** [comment]
@accessibleweb is this still the case?

**Comment by marianoguerra** [comment]
@adam-lynch it is for me trying 0.13.0, it works with 0.12.3

	Create cache folder in /home/mariano/src/work/FLT-Frontend/cache/0.13.0
	Downloading: http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-win-ia32.zip
	Create cache folder in /home/mariano/src/work/FLT-Frontend/cache/0.13.0
	Downloading: http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-win-x64.zip
	Create cache folder in /home/mariano/src/work/FLT-Frontend/cache/0.13.0
	Downloading: http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-osx-ia32.zip
	Create cache folder in /home/mariano/src/work/FLT-Frontend/cache/0.13.0
	Downloading: http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-osx-x64.zip
	Create cache folder in /home/mariano/src/work/FLT-Frontend/cache/0.13.0
	Downloading: http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-linux-x64.tar.gz
	  downloading [--------------------] 0% 349.2sERROR: The version 0.13.0 does not have a corresponding build posted at http://dl.nwjs.io/. Please choose a version from that list.

details:

* ubuntu 15.10
* nw-builder 2.2.0
* grunt-nw-builder 2.0.0

the weird part is that http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-linux-x64.tar.gz exists

**Comment by jgknott** [comment]
Same issue here.. The only version I can get to work is 0.12.3.

Looking in my .tmp directory, I can see that it's actually downloading the verisons but for some reason i'm still getting the error "Unable to download nodewebkit"

**Comment by evshiron** [comment]
See also: #319.

**Comment by adam-lynch** [comment]
Closing this in favour of #327. Thanks for reporting.
