### ISSUE TITLE
v 0.13.0 Command Line build issues ffmpegsumo

### ISSUE THREAD

**Issue by ARH-Digital** [nwjs/nw-builder#297]
I have tested this on two systems. 
OSX 10.11 and Windows 7

Building from the command line using ``nwbuild`` fails on v0.13.0 for win32 and win64. Error occuring is that ffmpegsumo.dll cannot be found. The file does not exist in the v13 builds, I am assuming it was replaced with ffmpeg.dll in v13, however the build script has not been updated to reflect this causing issues on build.

**Comment by bluelovers** [comment]
i think this can help u xd, and i too late see it lol
[https://github.com/nwjs/nw-builder/pulls](https://github.com/nwjs/nw-builder/pulls)

**Comment by tomlandia** [comment]
Solved by #281 and #296

**Comment by adam-lynch** [comment]
Closing this in favour of #327. Thanks for reporting.
