### ISSUE TITLE
App works with NW.exe but doesn't work when built with nw-builder

### ISSUE THREAD

**Issue by 0xFireball** [nwjs/nw-builder#299]
I am using this to build my application:
<pre>
var NwBuilder = require('nw-builder');
var nw = new NwBuilder({
    files: './app/**/*.*', // use the glob format
    platforms: ['linux64', 'osx64', 'win32', 'win64'],
    version: '0.12.3',
});

//Log stuff you want

nw.on('log',  console.log);

// Build returns a promise
nw.build().then(function () {
   console.log('all done!');
}).catch(function (error) {
    console.error(error);
});
</pre>

**My source files are in the `app/` subdirectory; when I run `nw app/`, the application loads and works correctly. When I build with `node build.js` (contents above), however, the output does not work (tested on Windows and Linux).**

Finally, the developer tools do not open with `gui.Window.get().showDevTools();` in the built executable while they do open while running `nw app/` (is this intentional?) This leaves me no way to debug exactly what is causing the application to work. Is there a way to debug built binaries?

**Comment by adam-lynch** [comment]
Hmm strange. What version is your `nw` dependency?

**Comment by 0xFireball** [comment]
the build script says `0.12.3
`

**Comment by 0xFireball** [comment]
The latest version of `nw-builder`, and the latest beta release of `NW.js`

**Comment by 0xFireball** [comment]
I have also noticed issues with resolution on high-DPI screens on Windows 10. I have confirmed this with the latest version of `nw-builder`.

**Comment by 0xFireball** [comment]
`nw-builder` also fails with an error about ffmpeg. I can give you the exact details if necessary/

**Comment by adam-lynch** [comment]
OK so some of this falls under #329 which we're focusing on now. Hopefully this'll be sorted soon for you.

About high-DPI issues... only with `nw-builder`? That would be very strange.

**Comment by 0xFireball** [comment]
Yes, high-dpi issues only with the builder. I am pretty sure this has to do with my specifying `0.12.3`, but I don't know as I have never used NW of that version. Doesn't the builder just download the release of the specified version? That would explain the high dpi issues.

However, once #329 is fixed, we can test out builder with newer versions of NW.
Unfortunately, the builder is lagging behind now and I have been using Electron to distribute my apps, even though I prefer NW.js's API to Electron's.

**Comment by 0xFireball** [comment]
This is the exact error (on Windows), as of the latest `nw-builder` from NPM:
{ Error: ENOENT: no such file or directory, lstat 'C:\Users\Fireball\AppData\Roaming\npm\node_modules\nw-builder\cache\0.16.0-beta1\win64\ffmpegsumo.dll'

**Comment by adam-lynch** [comment]
This should work as of today's latest version. Thanks for reporting.
