### ISSUE TITLE
Support renaming generated files

### ISSUE THREAD

**Issue by joneshf** [nwjs/nw-builder#30]
Thanks for this program! It has made working with node-webkit a bit easier.

I'd like to suggest that the generated files take on the application's name. In particular: `nw` on linux, `node-webkit.app` on osx and `nw.exe` on windows. If you're for it, I'll submit a PR, but It's a bit awkward to have this generate the specified names without knowing that's what's going to happen. From the README, it seems that the name supplied (or the one in the package.json) would be the name of the application when it was generated. You could still default it to the original names if not supplied anything. I've not found anything that states this isn't possible, and from testing, renaming seems to work on all os's.

Is there any reason why this isn't/can't be supported? If not, expect a PR soon.

**Comment by joneshf** [comment]
I've been out of the loop for a while. Is this still relevant or can the issue be closed?

**Comment by adam-lynch** [comment]
@joneshf >Is the long term solution to fix node webkit so that it doesn't require the executable to be named some arbitrary name?

Yes and I saw in an NW.js issue recently that they'd like to sort it for NW.js 0.13.0.

Not sure what the status of this issue is though tbh.
