### ISSUE TITLE
0.13.x builds not working

### ISSUE THREAD

**Issue by colinbes** [nwjs/nw-builder#300]
Was wondering if there was any feedback on issue of building modules for linux64. Seems there is still the issue of missing nw.pak file in downloaded files. 

I tired renaming file nw_100_percent.pak to nw.pak and that didn't help either.

**Comment by YacheLee** [comment]
I have the same problems.
My operating system is windows 7 based on 64 bits.

**Comment by hisune** [comment]
me too ...

**Comment by tomlandia** [comment]
Solved by #281 and #296.

**Comment by Sytten** [comment]
This is obviously not solved since its not merged. And I think it IS a serious issue since V0.13.X is now the STABLE version and the doc EXPLICITLY tells to use this tool.

**Comment by tomlandia** [comment]
Exactly, and this project is owned by the `nw` organisation 😳. WTF?

**Comment by Sytten** [comment]
I just asked on gitter, this is quite unacceptable

**Comment by tomlandia** [comment]
As a temporary fix, you can use one of these forks as a dependency in your `package.json`:

    "nw-builder": "git://github.com/jontro/nw-builder#nwjs-13",
    "nw-builder": "git://github.com/evshiron/nw-builder",

**Comment by Sytten** [comment]
Nice thanks

**Comment by Sytten** [comment]
Works good even with the new version (0.14.0)

**Comment by colinbes** [comment]
Just tried building nw for target version 0.13.4 and 0.14.0 and still see the nw.pak issue referenced above. I haven't tried tomlandia's suggested versions yet.

**Comment by Sytten** [comment]
You should... But I have new problems with plugins used in the code...

**Comment by zergius-eggstream** [comment]
As a temporary solution you can monkeypatch file `yourptojectpath\node_modules\nw-builder\lib\platforms.js`.
For example, for win32 platform you can change
```
'>=0.12.0': ['nw.exe', 'ffmpegsumo.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak', 'locales', 'd3dcompiler_47.dll', 'pdf.dll']
```
to
```
'>=0.12.0 <0.13.0': ['nw.exe', 'ffmpegsumo.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak', 'locales', 'd3dcompiler_47.dll', 'pdf.dll'],
'>=0.13.0': ['nw.exe', 'locales', 'd3dcompiler_47.dll', 'dbghelp.dll', 'ffmpeg.dll', 'icudtl.dat', 'libEGL.dll', 'libexif.dll', 'libGLESv2.dll', 'natives_blob.bin', 'node.dll', 'nw.dll', 'nw_100_percent.pak', 'nw_200_percent.pak', 'nw_elf.dll', 'resources.pak', 'snapshot_blob.bin']
```

**Comment by adam-lynch** [comment]
Closing this in favour of #327. Thanks for reporting.
