### ISSUE TITLE
Missing icon on OSX64 build

### ISSUE THREAD

**Issue by alterebro** [nwjs/nw-builder#303]
Build on osx64 ignores the macIcns option value when using versions higher than `0.12.3`.
I've tested the osx64 build with the following versions: `0.12.3`, `0.13.3`, `0.14.0-rc2` and `0.14.0-rc3`.
With `0.12.3` the icon is the one set on the `options.macIcns`, with the others the icon App is the default from NW.js

**Comment by cgallarno** [comment]
I've also encountered this issue, it seems that nwjs has renamed the default icon and nw-builder hasn't updated to name the icon to what nwjs expects, but it's still copying the icon into the Contents/Resources.
![screenshot 2016-04-11 10 32 33](https://cloud.githubusercontent.com/assets/597735/14430785/ec842a84-ffd0-11e5-92d7-876c823f18a1.png)

**Comment by sqwk** [comment]
Same here. It looks like this could easily be fixed in https://github.com/nwjs/nw-builder/blob/master/lib/index.js#L515

**Comment by nrdobie** [comment]
👍

**Comment by adam-lynch** [comment]
Fixed in #333

**Comment by adam-lynch** [comment]
Fixed as of version 2.2.1. Thanks.
