### ISSUE TITLE
Building for 0.14.1 does not read appname and copyright correctly

### ISSUE THREAD

**Issue by sqwk** [nwjs/nw-builder#308]
Building an app using 0.14.1 for osx64 ignores the appName (the created file is always called nwjs.app) and the copyright. (It is always "Copyright 2016 NW.js contributors, Chromium Authors, IO.js. All rights reserved.")

When creating a menu like this

    var mb = new nw.Menu({ type:"menubar" });
    mb.createMacBuiltin("Some Name");

The menu first lists the passed app name in the menu (the same as listed in the plist). Once the menu is modified, the app name in the menu reverts to "nwjs".

**Comment by adam-lynch** [comment]
I think this might be resolved by #337 and version 2.2.1. Thanks!
