### ISSUE TITLE
ffmpegsumo.dll missing

### ISSUE THREAD

**Issue by petermeester** [nwjs/nw-builder#309]
Hi guys,

Can someone explain me how I can fix the issue with building the app and the missing ffmpegsumo.dll file? I'm new to NW.js. When I building with 'nwbuild -p win32 -v 0.12.0' it works, but how to build it with v 0.13 ? Or the latest, v 0.14.1?

Thanks!

**Comment by evshiron** [comment]
Please take a look at #296 .

**Comment by petermeester** [comment]
@evshiron thanks!
