### ISSUE TITLE
don't force platforms

### ISSUE THREAD

**Issue by vankasteelj** [nwjs/nw-builder#310]
I'm surprised to see you've forced platforms in [/lib/index.js line 584](https://github.com/nwjs/nw-builder/blob/master/lib/index.js#L584):

    var platform = this._platforms[this.options.currentPlatform];

***

`this.options.currentPlatform` is set to the currentPlatform, and it prevents using a 32bit executable on 64bit osx or windows, when both support it.

You can atm build what you want, but you can't run it.

What I want to do, is `nw.run()` in my 64bit machine and let it load the 32bit executable, as the `options.platforms` states in the nw config object.

**Comment by vankasteelj** [comment]
What I could suggest is as simple as this, at line 30:

```
currentPlatform: options.currentPlatform | detectCurrentPlatform(),
```

allowing people (like me) to set a `currentPlatform` in the options, allowing us to do what we want, even if we risk breaking our local code because of bad platform detection (that's our problem :p)

**Comment by vankasteelj** [comment]
for information, this is the code I'm running to build what I want: https://github.com/butterproject/butter-desktop/blob/master/gulpfile.js#L36-L61

**Comment by marc136** [comment]
Hello @vankasteelj,

the currentPlatform argument is already available.
This snippet runs the 32bit executable on Win8.1 64bit:
```
var NwBuilder = require('nw-builder');

var options = {
    files: './*',
    platforms: ['win32'],
    currentPlatform: 'win32', // used for the run command
};

var nw = new NwBuilder(options);
nw.on('log', console.log);

nw.run().then(function() {
    console.log('finished');
});
```

Your commit changes the default value for currentPlatform (which is only used if no value was passed).
If the value is directly passed, it worked in my use case and it should also work on *nix.
That is why I think this issue is already solved.

**Comment by adam-lynch** [comment]
Sorry no one got back to you on this until now. @marc136 is correct. I have tweaked it a little bit (https://github.com/nwjs/nw-builder/commit/c0b664a39dbaefeda4d1aeb3fd1549abf2e34532) though. Previously, if you select to run an osx32 build (using `platforms`) and we detect you're on osx64, then it would fail. But now, we'll also try osx32 if you're on osx64. Same goes for Windows.
