### ISSUE TITLE
nw-download as dependency?

### ISSUE THREAD

**Issue by fritx** [nwjs/nw-builder#312]
Both of `electron-builder` and `electron-prebuilt` include `electron-download` as dependency.
I think it is better for `nw-builder` and [`nw`](https://github.com/nwjs/npm-installer) to include [`nw-download`](https://github.com/hughsk/nw-download) as dependency as well ;)

So that they can make use of the same cached nw prebuilt at the meantime (automatically), I guess :/

```js
// w/o configuring like this
new NwBuilder({
  cacheDir: './node_modules/nw/nwjs',  // './cache' by default
  // ...
})
```

Thoughts?
Cheers.

**Comment by evshiron** [comment]
`nw-download` has been inactive for 2 years (looks like it's still in the days of `node-webkit`), which is longer than `nw-builder` itself. It needs contributors' effort to make this happen (and maintainers as well).
The idea of sharing caches is nice though, I guess :/

**Comment by adam-lynch** [comment]
What @evshiron said. I'm definitely on board for sharing caches though and @rogerwang was too the last time we spoke.
