### ISSUE TITLE
Cannot use version of nwjs after v0.12.3

### ISSUE THREAD

**Issue by mato75** [nwjs/nw-builder#314]
Every time I run my test.js it starts to download the version and logs this:

ERROR: The version 0.14.2 does not have a corresponding build posted at http://dl.nwjs.io/. Please choose a version from that list.
Unable to download nodewebkit.

It tries again later and nwjs is downloaded, but it is never cached properly and it has to download the same version again.

**Comment by mato75** [comment]
Any suggestions please?

**Comment by evshiron** [comment]
@mato75 Please see #296.

**Comment by mato75** [comment]
Thx, I took a look and tried your suggestion, but I am still having problems. Now it does not download it again, it just says:

ERROR: The version 0.14.3 does not have a corresponding build posted at http://dl.nwjs.io/. Please choose a version from that list.
Unable to download nodewebkit. undefined

**Comment by evshiron** [comment]
@mato75 My fork should work. And it's recommended to uninstall previous versions before installing it, including both local and global ones. And could you please post your executed command, like `nwbuild -v 0.14.3-sdk -r .`, along with the output in a markdown code block?

**Comment by mato75** [comment]
I can get it to work on mac if I specified the osx64, but on linux, when I specify linux64, it downloads it, but when opening it, it just hard closes nw window with exit code 0

**Comment by mato75** [comment]
Ok got it to work, but this is a separate issue. Cannot run multiple instances with 14.3 version.

single-instance: false
