### ISSUE TITLE
nwjs v1.13.3 OS X Application name is always nwjs.

### ISSUE THREAD

**Issue by shripathee** [nwjs/nw-builder#315]
Facing a weird issue where the application display name is always 'nwjs', irrespective of the *name* field in package.json and the *appName* in the nw-builder config. When I do 'Get Info' on the file, the given application name and extension are shown correctly, but in Finder it's always 'nwjs'.

**Comment by evshiron** [comment]
See also #308.
Although the actual filename is `appName.app`, the display name is affected by both `Info.plist` and the i18n files located in `/Contents/Resources/`. In nw.js `0.12.x`, there is no i18n files so altering `Info.plist` is enough, but it won't work after `0.13.x`.

**Comment by sreuter** [comment]
@evshiron Name shows correctly then, but the app does crash and burn on startup then. `[43609:1295:0429/124054:FATAL:chrome_browser_main_mac.mm(114)] Check failed: !loaded_locale.empty(). Default locale could not be found`

**Comment by evshiron** [comment]
@sreuter I have tried `rm -r appName.app/Contents/Resources/*.lproj` with `0.14.1-sdk`, `0.14.2` and `0.15.1-beta1`, all of them work and I can't reappear your result. Make sure you remove only `*.lproj`, and leave `io.nwjs.nw.manifest` unchanged.
More information is appreciated.

**Comment by sreuter** [comment]
@evshiron Thanks for the fast feedback. You are right, my grunt cleanup task was accidentally deleting
./io.nwjs.nw.manifest/Contents/Resources/en.lproj, too.

**Comment by evshiron** [comment]
@sreuter 🎉

**Comment by adam-lynch** [comment]
I think this might be resolved by #337 and version 2.2.1. Thanks!
