### ISSUE TITLE
Windows Store Publish Issue

### ISSUE THREAD

**Issue by mohammadtorfehnezhad** [nwjs/nw-builder#317]
Hello all,

I created a windows app using nw-builder but when I tried to publish the app to windows store it's failed some certification steps based on following errors : 

>     File d3dcompiler_47.dll has failed the AppContainerCheck check.
>     File ffmpegsumo.dll has failed the AppContainerCheck check.
>     File libEGL.dll has failed the AppContainerCheck check.
>     File libGLESv2.dll has failed the AppContainerCheck check.
>     File pdf.dll has failed the AppContainerCheck check.
>     File application.exe has failed the AppContainerCheck check.

Has anybody tried this and has some solution for?

Thanks

**Comment by adam-lynch** [comment]
I'm not aware of anyone who has I'm afraid.

**Comment by adam-lynch** [comment]
I guess this would have a better chance of getting an answer in an NW.js issue / on the NW.js Google group or Gitter group.
