### ISSUE TITLE
No such file for directory ffmpegsumo.dll

### ISSUE THREAD

**Issue by craigbloodworth** [nwjs/nw-builder#320]
When building with nwjs v0.14.3 ffmpegsumo.dll is referenced by builder but isn't in the win32 package from nwjs.

{ [Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/nw-builder/cache/0.14.3/win32/ffmpegsumo.dll']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/usr/local/lib/node_modules/nw-builder/cache/0.14.3/win32/ffmpegsumo.dll' }

**Comment by evshiron** [comment]
Please see #296.

**Comment by atlantidezign** [comment]
FIX: in nw-builder/lib/platform.js replace the original code for win32 and win64 with this:

    win32: {
        needsZip: false,
        getRunnable: function() { return 'nw.exe'; },
        files: { // First file must be the executable
            '<=0.9.2': ['nw.exe', 'ffmpegsumo.dll', 'icudt.dll', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak'],
            '>0.9.2 <0.12.0': ['nw.exe', 'ffmpegsumo.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak', 'locales'],
			'>=0.12.0 <=0.12.3': ['nw.exe', 'ffmpegsumo.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak', 'locales', 'd3dcompiler_47.dll', 'pdf.dll'],
			'>0.12.3':['nw.exe', 'ffmpeg.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.dll', 'locales', 'd3dcompiler_47.dll', 'node.dll' , 'dbghelp.dll', 'libexif.dll', 'natives_blob.bin', 'nw_100_percent.pak', 'nw_200_percent.pak', 'nw_elf.dll', 'resources.pak', 'snapshot_blob.bin']
        },
        versionNameTemplate: 'v${ version }/${ name }-v${ version }-win-ia32.zip'
    },
    win64: {
        needsZip: false,
        getRunnable: function() { return 'nw.exe'; },
        files: { // First file must be the executable
            '<=0.9.2': ['nw.exe', 'ffmpegsumo.dll', 'icudt.dll', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak', 'locales'],
            '>0.9.2 <0.12.0': ['nw.exe', 'ffmpegsumo.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak', 'locales'],
            '>=0.12.0 <=0.12.3': ['nw.exe', 'ffmpegsumo.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.pak', 'locales', 'd3dcompiler_47.dll', 'pdf.dll'],
			'>0.12.3':['nw.exe', 'ffmpeg.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll', 'nw.dll', 'locales', 'd3dcompiler_47.dll', 'node.dll' , 'dbghelp.dll', 'libexif.dll', 'natives_blob.bin', 'nw_100_percent.pak', 'nw_200_percent.pak', 'nw_elf.dll', 'resources.pak', 'snapshot_blob.bin']
        },
        versionNameTemplate: 'v${ version }/${ name }-v${ version }-win-x64.zip'
    },

**Comment by evshiron** [comment]
Nice work but 0.13.x doesn't have a libexif.dll. And simply editing the `platforms.js` doesn't allow you to use the SDK/NaCl versions.
If you are interested please take a look at [evshiron/nw-builder](https://github.com/evshiron/nw-builder), which should work for 0.13.x/0.14.x and normal/SDK/NaCl versions, but doesn't work for 0.15.x and node.js 6.x currently (no time and no so much interest, PRs are welcomed though).
Is a good idea to use your fork as a temporary solution and merge the commits you need according to [nwjs/nw-builder/network](https://github.com/nwjs/nw-builder/network).

**Comment by piysingh** [comment]
Edit this line for win64 in platform.js in lib folder of nw-builder

'>=0.15.0': ['nw.exe', 'ffmpeg.dll', 'icudtl.dat', 'libEGL.dll', 'libGLESv2.dll','natives_blob.bin','nw_elf.dll','resources.pak','snapshot_blob.bin','node.dll','nw.dll', 'locales', 'd3dcompiler_47.dll','nw_100_percent.pak','nw_200_percent.pak','nw_material_100_percent.pak','nw_material_200_percent.pak']

This worked for me to package the application in with 0.15.0-rc2 version.

**Comment by adam-lynch** [comment]
Closing this in favour of #327. Thanks for reporting.
