### ISSUE TITLE
Please Upgrade packages for node 6.0.0

### ISSUE THREAD

**Issue by CxRes** [nwjs/nw-builder#321]
As you may know, [graceful-fs](https://github.com/isaacs/node-graceful-fs) <4.0.0 is no longer compatible with nodejs 6.0.0

Please update packages
- decompress-zip@0.0.8
- update-notifier@0.1.10

and after down stream update adam-lynch/graceful-ncp#2
- graceful-ncp@2.0.0

**Comment by evshiron** [comment]
Greeting. I have reimplement a [nwjs-builder](https://www.npmjs.com/package/nwjs-builder), which is built for node.js 4.x+, including node.js 6.x. It's basically compatible with the most used `nwbuild` options like `-v`, `-p` and `-r`, added with some other options like `--with-ffmpeg` and `--side-by-side`, and has fixed some pending issues of `nwjs/nw-builder`.
I am glad if you can try it out, and feedback is always welcome :)

**Comment by mato75** [comment]
I cannot access nwjs-builder url.

Error 503 backend read error

**Comment by adam-lynch** [comment]
Sorted on `phoenix` branch
