### ISSUE TITLE
Toolbar in 0.15.0

### ISSUE THREAD

**Issue by pettersonfaria** [nwjs/nw-builder#324]
I use the "toobar": true since 0.12.3 version, but now, the bar is hiden
Whats changed?
I try use require('nw.gui').Window.get().showDevTools(), but just a blank screen appear
Ref: https://github.com/nwjs/nw.js/wiki/debugging-with-devtools

**Comment by evshiron** [comment]
This issue has no relation with `nw-builder` itself.
Please read http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/.

**Comment by pettersonfaria** [comment]
Thank you.
Now "toolbar is deprecated" :(
I'll search for a replacement :/
