### ISSUE TITLE
Doesn`t work properly :(

### ISSUE THREAD

**Issue by scorpioRED** [nwjs/nw-builder#325]
Hi!
I have a small project based on node-webkit with 2 external node modules (for ssh and mikrotik api).
When I run it by 
     
> nodewebkit .

everything works fine.
Now I need to packed it in `exe` for using on `Windows 7`.
I tried build it using `nw-builder` (https://github.com/nwjs/nw-builder) with command bellow:
     

> nwbuild -p win32 my_app_dir

but I got an error :

> { [Error: ENOENT: no such file or directory, lstat
> '/Users/scorpio/01/0.15.0/win32/ffmpegsumo.dll']   errno: -2,   code:
> 'ENOENT',   syscall: 'lstat',   path:
> '/Users/scorpio/01/0.15.0/win32/ffmpegsumo.dll' }

Please help me

**Comment by evshiron** [comment]
@scorpioRED Greetings. `nwjs/nw-builder` only works with 0.12.x. Use https://www.npmjs.com/package/nwjs-builder if you are interested.

**Comment by joshterrill** [comment]
I ran into the same issue and added a pull request to add the latest version, `0.15.1` here: https://github.com/nwjs/nw-builder/pull/326

If you want to add support for a version you're using, it's pretty easy. Download the zip files of the version you want from http://dl.nwjs.io/, go into this file: https://github.com/nwjs/nw-builder/blob/master/lib/platforms.js and add your version along with an array of all of the files that it requires.

**Comment by adam-lynch** [comment]
Sorry about this. We'll get this fixed ASAP. 

Hey @evshiron, I've sent you an email (the email address on your npm account) :email: :eyes:

**Comment by adam-lynch** [comment]
Closing this in favour of #327. Thanks for reporting.
