### ISSUE TITLE
是不是不支持最新的nw.js打包？

### ISSUE THREAD

**Issue by linxu** [nwjs/nw-builder#332]
是不是只支持到nw version: '0.12.3'?最新的nw打包会出错！

**Comment by evshiron** [comment]
Yes. Feel free to look around Issues and PRs for solutions. The support for latest versions is on the plan too.

**Comment by linxu** [comment]
Nice. Hope to solve as soon as possible.

**Comment by adam-lynch** [comment]
Yes, I'm working on it. Closing in favour of #329.
