### ISSUE TITLE
after lauch meet error ' Uncaught ReferenceError: require is not defined '

### ISSUE THREAD

**Issue by aeolusheath** [nwjs/nw-builder#335]
```
Uncaught ReferenceError: require is not defined
```

and

```
Not allowed to load local resource: file:///tmp/.org.chromium.Chromium.xRDdKa/index.html
```

here my files:  package.json  index.html    and build.js

**package.json**:

```
{
  "name": "demo",
  "main": "./index.html",
  "version": "0.0.1",
  "window":{
	"show":true,
 	"frame":true
	}
}
```
**index.html**

```
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

    Home Page

</body>
</html>

```

**build.js**:
```
var NwBuilder = require('nw-builder');

var nw = new NwBuilder({
  files: './package.json',
  platforms: ['linux64'],
  version:'0.12.3'
});

nw.build().then(function(){
  console.log('done!');
}).catch(function(err){
  console.log(err);
});

```

I launch this app by this command:  *node build.js* 

![2016-06-30 16 52 03](https://cloud.githubusercontent.com/assets/5978548/16482587/0af997fa-3ee3-11e6-91e6-637f7bce1486.png)

@adam-lynch  bro  help

**Comment by adam-lynch** [comment]
@aeolusheath You're only giving nw-builder your `package.json`. So try:

```javascript
var nw = new NwBuilder({
  files: '*',
  platforms: ['linux64'],
  version:'0.12.3'
});
```

Or:

```javascript
var nw = new NwBuilder({
  files: ['./package.json', './index.html'],
  platforms: ['linux64'],
  version:'0.12.3'
});
```

Should be ok then 👍

**Comment by aeolusheath** [comment]
@adam-lynch  
bro  ,it works  . thanks

but I have a question .  I write a simple app  with about   10 + modules .  

should I write the build.js like this  :  
```
var nw = new NwBuilder({
  files: ['./package.json', './**/*'],
  platforms: ['linux64'],
  version:'0.12.3'
});
```

it succeed! but  the exe file is up to 1.7 G  !!! 

too large.   how can I minimize the exe file .....
