### ISSUE TITLE
Download version doesn't use proxy settings

### ISSUE THREAD

**Issue by DblK** [nwjs/nw-builder#341]
Hi,

When I try to download a new version of nwjs, the proxy configured in npm doesn't apply and so the download fail.
Would it be possible to detect proxy config and use it for downloading the cache executable?

**Comment by adam-lynch** [comment]
Could you give me more info on configuring the proxy in npm?

>Would it be possible to detect proxy config and use it for downloading the cache executable?

Can you give me an example of another module which does this?

**Comment by evshiron** [comment]
`nw-builder` uses `request` to download binaries and `request` supports `HTTP_PROXY`, `HTTPS_PROXY` and `ALL_PROXY` environment variables by default.
