### ISSUE TITLE
can not download nwjs NORMAL

### ISSUE THREAD

**Issue by fanchou** [nwjs/nw-builder#344]
i want nwjs NORAL not SDK

`generatePlatformUrls = function(version, supportedPlatforms){
            var platformUrls = {};
            supportedPlatforms.forEach(function(platform){
                platformUrls[platform] = args.downloadUrl + 'v' + version + '/nwjs-sdk-v' + version + '-' + fixPlatformName(platform)
                    + '.' + mapPlatformToExtension(platform);
            });
            return platformUrls;
        };
`

always download SDK

**Comment by DblK** [comment]
Hi, there is my pull request #340 that solve this.
Actually, the new version is to be back on track and mimic the previous version.
For now, sdk only, when my pull request will be merged we will have normal and sdk flavor.
Just wait until the maintainer merge it ;)

**Comment by fanchou** [comment]
@DblK oh,thanks

**Comment by adam-lynch** [comment]
Yes this is coming. The plan outlined in #327. Thanks.
