### ISSUE TITLE
osx64 app will not start

### ISSUE THREAD

**Issue by MichalMisiaszek** [nwjs/nw-builder#346]
The generated .app will not start on OSX, the message: 
You can’t open the application “XXX.app” because it may be damaged or incomplete.

**Comment by adam-lynch** [comment]
Can you give me your Node version and the version of NW.js version you're building for?

Even better, could you give me an example project?

**Comment by MichalMisiaszek** [comment]
Sorry I can't give you my project but it is pretty standard. I am using NWJS version 0.16.

**Comment by adam-lynch** [comment]
@MichalMisiaszek OK. I've just built an app with 0.16.0 a couple of minutes ago and it seems fine. If you can't give an example project, how about the other way around? How about you try building an app from the example (in the [`/example` directory](https://github.com/nwjs/nw-builder/tree/master/example))?

Don't forget to change the version option to `0.16.0` and the platforms option to `['osx64']`.

**Comment by MichalMisiaszek** [comment]
I will, give me a few minutes.

**Comment by MichalMisiaszek** [comment]
OK, I tried to build my project with option -v ( I did not used it before) and now error message is different: You can’t open the application “STL GUI.app” because it is not supported on this type of Mac. 
I will try to download example and try, I intalled

**Comment by MichalMisiaszek** [comment]
OK, i tried /example and got the same error. I tried other tools also for building and was getting the same error as above.

**Comment by MichalMisiaszek** [comment]
The only way I managed to build application was to put files inside app.nw

**Comment by adam-lynch** [comment]
There must be something different about your app that's causing this :/

**Comment by MichalMisiaszek** [comment]
but I tired /example as well.

**Comment by adam-lynch** [comment]
OK sorry. What happened when you tried the example? Which version of node and nw-builder?

**Comment by MichalMisiaszek** [comment]
Node is a part of NWJS, but I assume 5.4.1. 
nw-builder the newest I assume installed with npm
The result is the same.

**Comment by adam-lynch** [comment]
You've a different instance of node installed on your machine. Run `node -v`. If nw-builder is installed globally, you can get the version  with `npm list -g nw-builder`.

**Comment by MichalMisiaszek** [comment]
node --version
v5.4.1
npm list -g nw-builder
/usr/local/lib
└── nw-builder@2.2.5

**Comment by adam-lynch** [comment]
To confirm, when you tried the example, you got `You can’t open the application “STL GUI.app” because it is not supported on this type of Mac.`?

**Comment by MichalMisiaszek** [comment]
Yes

**Comment by MichalMisiaszek** [comment]
same for example: You can’t open the application “example.app” because it is not supported on this type of Mac. 
It is big app but I could upload for you to try on your machine.

**Comment by adam-lynch** [comment]
The example can't open because it's not supported? That's reaaaallly weird. Has nw-builder ever worked for you? Does a download from nwjs.io open for you?

If so, can you try installing nw globally (`npm i -g nw`) and run `nw .` in the `/example/nwapp` directory?

**Comment by MichalMisiaszek** [comment]
nwjs.io works very well. I suspect there must be some mess-up with versions or installations. 
I installed as you suggested and can't start example:
```
nw .
/SourceCache/AppleGVA/AppleGVA-8.4.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4
/SourceCache/AppleGVA/AppleGVA-8.4.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5
/SourceCache/AppleGVA/AppleGVA-8.4.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 6
/SourceCache/AppleGVA/AppleGVA-8.4.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 7
```

**Comment by adam-lynch** [comment]
Yeah there's something weird going on here. I have no idea what that path relates to so it seems it's something wrong with your machine. Although the NW.js example worked so I'm not sure. It could be your node, so I'd try re-installing that.

**Comment by MichalMisiaszek** [comment]
Just node or nwjs ?

**Comment by adam-lynch** [comment]
Node itself. The one on your machine (`i.e. node -v`) not the one in any NW.js app.

**Comment by MichalMisiaszek** [comment]
Reinstalled node it did not helped :(. My app is complaining but opening the screen, example don't.
