### ISSUE TITLE
Downloads are not cached

### ISSUE THREAD

**Issue by kessler** [nwjs/nw-builder#350]
On my system (OSX, nwjs 0.12.3, nw-builder 2.2.5), nwjs downloads are not cached.

I traced the problem to this code section:
```javascript
// if the version is >=0.12.3, then we don't which files we want from the archives, so just check that the folder
// exists and has at least 4 files in it.
if(files.length === 1 && files[0] === '*'){
    return fs.existsSync(cachepath) && fs.readdirSync(cachepath).length > 3;
}
```
https://github.com/nwjs/nw-builder/blob/master/lib/downloader.js#L27

On my machine ```fs.readdirSync(cachepath).length``` equals exactly 3, if I change ```>``` to ```>=``` everything works. Any ideas as to why this is happening?

**Comment by adam-lynch** [comment]
Yeah I had my doubts when changing this. For legacy NW.js versions we had a harcoded list of files in the ZIPs (downloaded from nwjs.io) and to check if the desired version was downloaded and cached successfully previously, we'd check if all of the files in the hardcoded files were there. For newer versions, we don't keep a manifest at all so we can't really check if all the files are there. I thought checking if at least 4 files were there was safe. Which target platform is that failing for? Linux? 

Anyway, I guess all we can do is change it like you said. Want to make a pull-request?

**Comment by kessler** [comment]
It's osx and PR is on the way

**Comment by kessler** [comment]
@adam-lynch PR ready :)
