### ISSUE TITLE
Query : to zip or not to zip ? ( Windows platform )

### ISSUE THREAD

**Issue by bhavyaw** [nwjs/nw-builder#352]
I am trying to create a build for windows ( win64 ) . On initial attempts the load time was around 15s but after adding 

`zip : false` 

in options the the app is instantly loaded. 

So, in regard to that i have a few queries :

1. What are the advantages of zipping  files into executable. 
2. Are there any ramifications that we should be aware of in case we don't ( `zip : false` ) zip files. Is it ok for production purposes i.e sending out builds to users ?

**Comment by adam-lynch** [comment]
I'm no expert on this area but as far as I know, the only downside is that the app would be larger (i.e. what your users will have to download). I hope that clears it up.
