### ISSUE TITLE
Build size too large 

### ISSUE THREAD

**Issue by bhavyaw** [nwjs/nw-builder#353]
I was able to successfully create the build for windows platform but the build folder size is 135 mb. Which i feel is quite large considering my code base and dependencies i have used.

There's one file in particular i.e `nw.dll` which is alone of 91MB ( as shown in the image below ). 
 
- Any ideas about how can i go and reduce the build size ? esp that of nw.dll file.
- Will minifying and concatenation of dependencies ( bower_components, node_modules ) will help in this regard ?

**Build Directory Structure**

![filesize](https://cloud.githubusercontent.com/assets/6906721/17519176/69643d50-5e68-11e6-8a6b-f93e75dced1c.png)

Details : 

- Platform : windows 10
- node webkit version : 0.14.3
- Dependencies
 "dependencies": {
    "bindings": "^1.2.1",
    "dexie": "^1.3.6",
    "fs": "0.0.2",
    "q": "^1.4.1"
  },
  "devDependencies": {
    "nan": "^2.3.3"
  },

Please let me know if can provide any further information.

**Comment by adam-lynch** [comment]
This is just the nature of NW.js. It does contain Chromium and Node.js after all.

>Any ideas about how can i go and reduce the build size ? esp that of nw.dll file.

As far as I know, you can't do anything about `nw.dll`.

>Will minifying and concatenation of dependencies ( bower_components, node_modules ) will help in this regard ?

Yes, but ultimately the base NW.js is large.

This is more of a problem with NW.js. I'll close this. You should create an issue in the NW.js project (although I can tell you now that you won't really get anywhere). Sorry about that.
