### ISSUE TITLE
Some node webkit arguments are being ignored by builder

### ISSUE THREAD

**Issue by onderaltintas** [nwjs/nw-builder#354]
Some of the arguments in package.json are being completely ignored.
For example:
"nodejs": true/false
"chromium-args": "..."

These are being used often for node webkit and yet they do not have effect for nwbuilder. Especially for cross domain requests, right now there is no way to fix cors error because of nodejs argument is being ignored. 

See:
Version 13+:
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Security%20in%20NW.js/
Version 13-:
https://github.com/nwjs/nw.js/wiki/manifest-format

**Comment by adam-lynch** [comment]
Hmm... this should be working. Can you give an example of your `package.json`?

**Comment by onderaltintas** [comment]
Sure, actually maybe it could be a node webkit issue, because getmack node module works well with this package.json but the cross origin requests are not working when I compile with nw builder as it is working with standalone 13+ and 13- versions of nw. Here is my package.json:

{
  "main": "public/index.html",
  "name": "aaa",
  "version": "1.0.0",
  "window": {
    "icon": "aaa.png",
    "title": "aaa",
    "toolbar": false,
    "frame": false,
    "kiosk": true
  },
  "webkit": {
    "plugin": true
  },
  "dependencies": {
    "getmac":"~1.0.7"
  },
  "chromium-args": "--disable-web-security --user-data-dir",
  "nodejs": true
}

**Comment by adam-lynch** [comment]
@onderaltintas I think so too. Not all Chromium flags are supported with NW.js (I'm not sure which are or not). I'd suggest creating an issue with the NW.js project / ask in the Google group. Thanks.
