### ISSUE TITLE
App cannot build for osx32

### ISSUE THREAD

**Issue by bengyles** [nwjs/nw-builder#363]
Windows, Linux and osx64 were successful but the osx32 platform would not build. When I try to build this one I get the error message: [Error: Unsupported NW.js version '0.17.3 (sdk)' for platform 'osx32'].

**Comment by DblK** [comment]
For osx, only 64 bit version exist so using nw-builder you can't build for 32 bits.

It's not an issue.

**Comment by bengyles** [comment]
Ok sorry to bother you then... But why is it in the docs then? I just copied it without knowing it does not exist :)

**Comment by DblK** [comment]
No problem.
The 32 bits version works but only with legacy version and it is not and probably won't be supported anymore.
That's why it exists in the docs.

Hope I answered all your questions.

**Comment by adam-lynch** [comment]
:+1: we should update the docs and maybe the code to warn you.

**Comment by bengyles** [comment]
Ok thank you very much, I built my google chrome app for Windows, Mac and Linux and it all seems to work fine. Awesome work guys!

**Comment by julmot** [comment]
The docs still don't include this information.

**Comment by DblK** [comment]
I just update the doc, still need a warning in the program.

**Comment by MaffooBristol** [comment]
I got this error, but my processor is definitely 64 bits. I'm reworking an old project and I think a very old version just had `osx` as a platform name, but now it requires `osx64`.
