### ISSUE TITLE
[Question] How can I pass command line arguments?

### ISSUE THREAD

**Issue by y-ich** [nwjs/nw-builder#375]
Hi.

When I invoke my osx64 app by nw-builder with command line argment, I got an error below.
(Actually reproduction condition is a little more complicated, you should pass existing file name as the argument.)

    [1005/161432:FATAL:chrome_main_delegate.cc(530)] Failed to load node library (error: dlopen(/Applications/WGo Editor.app/Contents/Versions/53.0.2785.143/nwjs Framework.framework/libnode.dylib, 1): Library not loaded: @executable_path/../../../nwjs Framework.framework/nwjs Framework
      Referenced from: /Applications/WGo Editor.app/Contents/Versions/53.0.2785.143/nwjs Framework.framework/libnode.dylib
      Reason: image not found)
    Trace/BPT trap: 5

Since @executable_path is /Applications/<MY APP>/Contents/MacOS/, it seems that libnode.dylib requires /Applications/nwjs Framework.framework/nwjs Framework.
I made a symbolic link in /Applications and could avoid the problem.

But I found that nwjs assumes that the first argument is a kind of startup.js file (not html file).
How can I pass usual command line arguments to my app?

**Comment by adam-lynch** [comment]
Hey @y-ich, this isn't really specific to nw-builder. You should create an issue over in the [NW.js issue tracker](https://github.com/nwjs/nw.js/issues) or use the [Google group](https://groups.google.com/forum/#!forum/nwjs-general).

**Comment by y-ich** [comment]
Sorry for my misunderstanding.
I will do your advice.
