### ISSUE TITLE
Use common directory for cache.

### ISSUE THREAD

**Issue by libook** [nwjs/nw-builder#394]
I have many nw project.
And each project directory have their own cache directory.
These content are the same.
So is there any way to use a common directory to storage these cache?

I found an option option.cacheDir.
But it seems doesn't support '~' to locate home directory.

**Comment by nrleuenb** [comment]
If you're on a mac, try /Users/username instead. C:\Users\username on windows.

**Comment by libook** [comment]
I need to write common scripts to build each project. And each developers has different 'username'.
Any advice?

**Comment by nrleuenb** [comment]
How are you getting the username? 

I'd recommend using the [untildify](https://www.npmjs.com/package/untildify) package, which will transform a tilde path to an absolute path. There's also a package called path that you can use to join /User/ or C:\Users\ and <username>. 
It depends on how you intend to implement it, but untildify sounds like the best option.

**Comment by adam-lynch** [comment]
Sounds like this is under control. Thanks @nrleuenb!
