### ISSUE TITLE
Change executable description 

### ISSUE THREAD

**Issue by pablozandona** [nwjs/nw-builder#395]
Can I change the description that is in task manager and others places in Windows?

![task](https://cloud.githubusercontent.com/assets/5611322/20113526/e485e194-a5d7-11e6-8ee9-32cb9f42ee73.PNG)

**Comment by asuhov** [comment]
You can use node-rcedit module to change FileDescription, ProductName and other properties of nw.exe file from NW.js package. These properties will get into your .exe file after build.

**Comment by pablozandona** [comment]
Works fine! The file properties was changed.
But the package files disappeared, the nwjs go back to default application, without my files.

**Comment by asuhov** [comment]
You should change the properties of the nw.exe file from NW.js package (it's usually located at the "cache" folder) and only after that build you own application using nw-builder. In this case your files will remain.
Maybe there is a better solution.

**Comment by pablozandona** [comment]
Works fine! Thanks!
