### ISSUE TITLE
Linux executable interpreted as application/x-sharedlib by Nautilus

### ISSUE THREAD

**Issue by marckris** [nwjs/nw-builder#401]
First off, thanks a million for this great app!

I have a minor issue though. My client's app is a promotional app distributed on CD. Building for Linux on Ubuntu 16.04, the executable is something like MyApp (with no extension) and is interpreted by Nautlus as application/x-sharedlib thus double clicking on it will not run the app.

After trying various things, I have found that renaming the app by giving it the .sh extension (MyApp.sh) sovles the problem. Now Nautilus is interpreting it as application/x-shellscript and I can double click on it to run it.

My question: is this the proper way to do it or am I missing something?

Thanks in advance.

**Comment by ghostoy** [comment]
A `.desktop` file might solve your issue. See https://github.com/nwjs/nw.js/issues/5287#issuecomment-245825930.

**Comment by marckris** [comment]
Will close this and switch to https://github.com/nwjs/nw.js/issues/5287
