### ISSUE TITLE
Build .exe ignores url CLI argument

### ISSUE THREAD

**Issue by ReSpawN** [nwjs/nw-builder#405]
After building an x64 win executable, the --url CLI argument is ignored. Is it just me?

**Comment by julmot** [comment]
@ReSpawN Where do you take `--url` from? According to [the docs](https://github.com/nwjs/nw-builder#usage) this argument isn't available.

**Comment by ReSpawN** [comment]
True, but I was hoping for some kind of passthru. I've been able to solve it my improving my app with an ini reader so all is good. I still think a builder run script would be an improvement so that you can bootup with --url which is NWJS compatible.
