### ISSUE TITLE
MacOS version of the package will be repeated every time!!!

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw-builder#407]
Local clearly has been downloaded, but every time it will be repeated to download the MacOS version of the program package!!!
The Windows version of the installation package does not exist this problem!

**Comment by cupofnestor** [comment]
I'm having this problem as well.

**Comment by nrleuenb** [comment]
Did you change it to 0.19.2-sdk? I was having that issue and I noticed that once I changed it (and had the fully qualified filepath) that I no longer had it redownloading instead of using the cached file

**Comment by adam-lynch** [comment]
@nrleuenb are you saying it's caching for that version but not `latest`?

**Comment by nrleuenb** [comment]
@adam-lynch I haven't tried using `latest`. I download specific versions from the FTP server, and save them to a custom cache folder. I've noticed that if the name doesn't include "-sdk" it will download from the server, unlike previous behavior.

**Comment by adam-lynch** [comment]
@nrleuenb huh I've no idea why you do that but OK 👍 😄. Yeah, the flavour is appended to the cache directory. Since @phpjishu thumbed up your solution, I'll close this. If this issue still persists, let me know. Thanks

**Comment by nrleuenb** [comment]
@adam-lynch My application needs to run as administrator, so I manually modify the manifests to require Administrator trust levels, as my users often forget to run it as admin. Any suggestions on how to do it better? I haven't come across anything so far.
