### ISSUE TITLE
Windows .exe not generating

### ISSUE THREAD

**Issue by nrleuenb** [nwjs/nw-builder#408]
I'm trying to generate a new build on Windows, and while it appears to go through the entire build process with no issues, renaming the .exe, etc., when I attempt to open the .exe I just see the default screen. 
My current assumption is that nw-builder doesn't support nwjs 0.19.2, but I have no issues generating a Mac application.
Is anyone else having this issue? Is it just that nw-builder doesn't support the latest version of nwjs?

**Comment by adam-lynch** [comment]
Out of curiosity, how did you resolve this? I see you closed the issue the next day.

**Comment by nrleuenb** [comment]
I don't remember how I solved it.... I think there was an issue with my build scripts, but I don't remember the specifics. I don't think it was an issue with nwjs-builder which is why I closed it.

**Comment by adam-lynch** [comment]
:+1:
