### ISSUE TITLE
Unable to download NWjs

### ISSUE THREAD

**Issue by bramblex** [nwjs/nw-builder#418]
I got some troubles when building with following script. It always throw "Unable to download Nwjs", but i can download it by wget.

``` JavaScript 
// build.js
 var NwBuilder = require('nw-builder');          
 var nw = new NwBuilder({
     files: './src/**/**', // use the glob format
     platforms: ['linux64'],
     version: '0.14.6'
 });
  
 //Log stuff you want
  
 nw.on('log',  console.log);
  
 // Build returns a promise
 nw.build().then(function () {
    console.log('all done!');
 }).catch(function (error) {
     console.error(error);
 });
```

```
(node:20081) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Using v0.14.6 (sdk)
Create cache folder in /tmp/test/cache/0.14.6-sdk
Downloading: http://dl.nwjs.io/v0.14.6/nwjs-sdk-v0.14.6-linux-x64.tar.gz
undefined
Unable to download NWjs.
```

**Comment by rogerwang** [comment]
It should be the change on the server side made today, which redirects all HTTP traffic to HTTPS.

should I revert it and wait for the update of nw-builder?

**Comment by schuhschuh** [comment]
This can be fixed on the users side by adding the option `downloadUrl: 'https://dl.nwjs.io/'` to your build script. This overwrites the default that uses HTTP.

**Comment by bastimeyer** [comment]
I have submitted a PR (#355) for default https downloads (and a `manifestUrl` option) a couple of months ago, but it seems that development of the builder has gone stale again...

**Comment by AndrewTrefethen** [comment]
for now, you can change the download link in the lib/index.js file line 35.

change it to 'https://dl.nwjs.io/' and you should be able to build.

thanks to schuhschuh for putting me on the right track.

**Comment by JerryChin** [comment]
I meet this problem today.

**Comment by zhailei31665431** [comment]
+1

**Comment by julmot** [comment]
+1 Should be fixed ASAP

**Comment by adam-lynch** [comment]
nw-builder should now default to HTTPS as of version 3.2.0. Thanks @bastimeyer for the PR; https://github.com/nwjs/nw-builder/pull/355
