### ISSUE TITLE
Anolis Resourcer Program has stopped working

### ISSUE THREAD

**Issue by 1j01** [nwjs/nw-builder#72]
![image](https://cloud.githubusercontent.com/assets/3630663/4192345/15636090-3797-11e4-9a50-3968f893f08e.png)

**Description:**
  Stopped working *(wow thanks)*

**Problem signature:**
  Problem Event Name:	CLR20r3
  Problem Signature 01:	resourcer.exe
  Problem Signature 02:	0.9.3531.38736
  Problem Signature 03:	4a9d92b4
  Problem Signature 04:	mscorlib
  Problem Signature 05:	2.0.0.0
  Problem Signature 06:	530eec86
  Problem Signature 07:	34a9
  Problem Signature 08:	119
  Problem Signature 09:	System.IO.DirectoryNotFound
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033

**Read our privacy statement online:**
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

#### Command line output:
```
bla bla bla
Update executable icon
```
\*close program\*
```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Isaiah\AppData\Local\Anolis\Exceptions.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at Anolis.Resourcer.Program.Main(String[] args)
Error while updating the Windows icon.
```

**Comment by cktech529** [comment]
This issue is old and I just reproduced it 1/5/2016 (first time I saw it)

build_and_package_the_demo_on_windows:
     [copy] Copying 9 files to C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages
    [unzip] Expanding: C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages\node_modules.zip into C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages
     [copy] Copying 1 file to C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages
     [copy] Copying 1 file to C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages
     [exec]         1 file(s) copied.
     [exec]
     [exec] > EMCUnityDemo@1.0.0 gulp C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages
     [exec] > gulp
     [exec]
     [exec] [09:34:35] Using gulpfile C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages\gulpFile.js
     [exec] [09:34:35] Starting 'nw'...
     [exec] [09:34:37] nw-builder Using v0.12.3
     [exec] [09:34:37] nw-builder Create cache folder in C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages\cache\0.12.3
     [exec] [09:34:37] nw-builder Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-win-x64.zip
     [exec] [09:34:37] nw-builder Create cache folder in C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages\cache\0.12.3
     [exec] [09:34:37] nw-builder Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-osx-x64.zip
     [exec]
     [exec]
     [exec] [09:35:14] nw-builder Create release folder in C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages\build\EMCUnityDemo\win64
     [exec] [09:35:14] nw-builder Create release folder in C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages\build\EMCUnityDemo\osx64
     [exec] [09:35:17] nw-builder chmod 33206 on C:\views\NEXTGE~2\nxgui\NxGenWorkspace\build\CemGui\demoPackages\build\EMCUnityDemo\osx64\EMCUnityDemo.app\Contents\Resources\nw.ic
ns failed after copying, ignoring
     [exec] [09:35:18] nw-builder Update win64 executable icon
     [exec]
     [exec] Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\kingc5\AppData\Local\Anolis\Exceptions.log'.
     [exec]    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     [exec]    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options,
SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
     [exec]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromPro
xy)
     [exec]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     [exec]    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
     [exec]    at System.IO.StreamWriter..ctor(String path, Boolean append)
     [exec]    at Anolis.Resourcer.Program.Main(String[] args)
     [exec] [09:35:26] nw-builder Error while updating the Windows icon.
     [exec] [09:35:26] Finished 'nw' after 51 s
     [exec] [09:35:26] Starting 'default'...
     [exec] [09:35:26] Finished 'default' after 12 ╬╝s

**Comment by AndrewMast** [comment]
Same problem

**Comment by adam-lynch** [comment]
I don't think there's anything wrong with nw-builder's usage of winresourcer. I'll have to close this. More success might be had if it was reported to winresourcer, etc. Thanks anyway.
